# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@alloc/quick-lru-5.2.0" = {
      name = "_at_alloc_slash_quick-lru";
      packageName = "@alloc/quick-lru";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@alloc/quick-lru/-/quick-lru-5.2.0.tgz";
        sha512 = "UrcABB+4bUrFABwbluTIBErXwvbsU/V7TZWfmbgJfbkwiBuziS9gxdODUyuiecfdGQ85jglMW6juS3+z5TsKLw==";
      };
    };
    "@cspotcode/source-map-support-0.8.1" = {
      name = "_at_cspotcode_slash_source-map-support";
      packageName = "@cspotcode/source-map-support";
      version = "0.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cspotcode/source-map-support/-/source-map-support-0.8.1.tgz";
        sha512 = "IchNf6dN4tHoMFIn/7OE8LWZ19Y6q/67Bmf6vnGREv8RSbBVb9LPJxEcnwrcwX6ixSvaiGoomAUvu4YSxXrVgw==";
      };
    };
    "@isaacs/cliui-8.0.2" = {
      name = "_at_isaacs_slash_cliui";
      packageName = "@isaacs/cliui";
      version = "8.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@isaacs/cliui/-/cliui-8.0.2.tgz";
        sha512 = "O8jcjabXaleOG9DQ0+ARXWZBTfnP4WNAqzuiJK7ll44AmxGKv/J2M4TPjxjY3znBCfvBXFzucm1twdyFybFqEA==";
      };
    };
    "@jridgewell/gen-mapping-0.3.5" = {
      name = "_at_jridgewell_slash_gen-mapping";
      packageName = "@jridgewell/gen-mapping";
      version = "0.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/gen-mapping/-/gen-mapping-0.3.5.tgz";
        sha512 = "IzL8ZoEDIBRWEzlCcRhOaCupYyN5gdIK+Q6fbFdPDg6HqX6jpkItn7DFIpW9LQzXG6Df9sA7+OKnq0qlz/GaQg==";
      };
    };
    "@jridgewell/resolve-uri-3.1.2" = {
      name = "_at_jridgewell_slash_resolve-uri";
      packageName = "@jridgewell/resolve-uri";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/resolve-uri/-/resolve-uri-3.1.2.tgz";
        sha512 = "bRISgCIjP20/tbWSPWMEi54QVPRZExkuD9lJL+UIxUKtwVJA8wW1Trb1jMs1RFXo1CBTNZ/5hpC9QvmKWdopKw==";
      };
    };
    "@jridgewell/set-array-1.2.1" = {
      name = "_at_jridgewell_slash_set-array";
      packageName = "@jridgewell/set-array";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/set-array/-/set-array-1.2.1.tgz";
        sha512 = "R8gLRTZeyp03ymzP/6Lil/28tGeGEzhx1q2k703KGWRAI1VdvPIXdG70VJc2pAMw3NA6JKL5hhFu1sJX0Mnn/A==";
      };
    };
    "@jridgewell/source-map-0.3.6" = {
      name = "_at_jridgewell_slash_source-map";
      packageName = "@jridgewell/source-map";
      version = "0.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/source-map/-/source-map-0.3.6.tgz";
        sha512 = "1ZJTZebgqllO79ue2bm3rIGud/bOe0pP5BjSRCRxxYkEZS8STV7zN84UBbiYu7jy+eCKSnVIUgoWWE/tt+shMQ==";
      };
    };
    "@jridgewell/sourcemap-codec-1.5.0" = {
      name = "_at_jridgewell_slash_sourcemap-codec";
      packageName = "@jridgewell/sourcemap-codec";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/sourcemap-codec/-/sourcemap-codec-1.5.0.tgz";
        sha512 = "gv3ZRaISU3fjPAgNsriBRqGWQL6quFx04YMPW/zD8XMLsU32mhCCbfbO6KZFLjvYpCZ8zyDEgqsgf+PwPaM7GQ==";
      };
    };
    "@jridgewell/trace-mapping-0.3.25" = {
      name = "_at_jridgewell_slash_trace-mapping";
      packageName = "@jridgewell/trace-mapping";
      version = "0.3.25";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/trace-mapping/-/trace-mapping-0.3.25.tgz";
        sha512 = "vNk6aEwybGtawWmy/PzwnGDOjCkLWSD2wqvjGGAgOAwCGWySYXfYoxt00IJkTF+8Lb57DwOb3Aa0o9CApepiYQ==";
      };
    };
    "@jridgewell/trace-mapping-0.3.9" = {
      name = "_at_jridgewell_slash_trace-mapping";
      packageName = "@jridgewell/trace-mapping";
      version = "0.3.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/trace-mapping/-/trace-mapping-0.3.9.tgz";
        sha512 = "3Belt6tdc8bPgAtbcmdtNJlirVoTmEb5e2gC94PnkwEW9jI6CAHUeoG85tjWP5WquqfavoMtMwiG4P926ZKKuQ==";
      };
    };
    "@nodelib/fs.scandir-2.1.5" = {
      name = "_at_nodelib_slash_fs.scandir";
      packageName = "@nodelib/fs.scandir";
      version = "2.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nodelib/fs.scandir/-/fs.scandir-2.1.5.tgz";
        sha512 = "vq24Bq3ym5HEQm2NKCr3yXDwjc7vTsEThRDnkp2DK9p1uqLR+DHurm/NOTo0KG7HYHU7eppKZj3MyqYuMBf62g==";
      };
    };
    "@nodelib/fs.stat-2.0.5" = {
      name = "_at_nodelib_slash_fs.stat";
      packageName = "@nodelib/fs.stat";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nodelib/fs.stat/-/fs.stat-2.0.5.tgz";
        sha512 = "RkhPPp2zrqDAQA/2jNhnztcPAlv64XdhIp7a7454A5ovI7Bukxgt7MX7udwAu3zg1DcpPU0rz3VV1SeaqvY4+A==";
      };
    };
    "@nodelib/fs.walk-1.2.8" = {
      name = "_at_nodelib_slash_fs.walk";
      packageName = "@nodelib/fs.walk";
      version = "1.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nodelib/fs.walk/-/fs.walk-1.2.8.tgz";
        sha512 = "oGB+UxlgWcgQkgwo8GcEGwemoTFt3FIO9ababBmaGwXIoBKZ+GTy0pP185beGg7Llih/NSHSV2XAs1lnznocSg==";
      };
    };
    "@rollup/plugin-terser-0.4.4" = {
      name = "_at_rollup_slash_plugin-terser";
      packageName = "@rollup/plugin-terser";
      version = "0.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@rollup/plugin-terser/-/plugin-terser-0.4.4.tgz";
        sha512 = "XHeJC5Bgvs8LfukDwWZp7yeqin6ns8RTl2B9avbejt6tZqsqvVoWI7ZTQrcNsfKEDWBTnTxM8nMDkO2IFFbd0A==";
      };
    };
    "@swc/core-1.7.42" = {
      name = "_at_swc_slash_core";
      packageName = "@swc/core";
      version = "1.7.42";
      src = fetchurl {
        url = "https://registry.npmjs.org/@swc/core/-/core-1.7.42.tgz";
        sha512 = "iQrRk3SKndQZ4ptJv1rzeQSiCYQIhMjiO97QXOlCcCoaazOLKPnLnXzU4Kv0FuBFyYfG2FE94BoR0XI2BN02qw==";
      };
    };
    "@swc/counter-0.1.3" = {
      name = "_at_swc_slash_counter";
      packageName = "@swc/counter";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@swc/counter/-/counter-0.1.3.tgz";
        sha512 = "e2BR4lsJkkRlKZ/qCHPw9ZaSxc0MVUd7gtbtaB7aMvHeJVYe8sOB8DBZkP2DtISHGSku9sCK6T6cnY0CtXrOCQ==";
      };
    };
    "@swc/helpers-0.5.13" = {
      name = "_at_swc_slash_helpers";
      packageName = "@swc/helpers";
      version = "0.5.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@swc/helpers/-/helpers-0.5.13.tgz";
        sha512 = "UoKGxQ3r5kYI9dALKJapMmuK+1zWM/H17Z1+iwnNmzcJRnfFuevZs375TA5rW31pu4BS4NoSy1fRsexDXfWn5w==";
      };
    };
    "@swc/types-0.1.13" = {
      name = "_at_swc_slash_types";
      packageName = "@swc/types";
      version = "0.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@swc/types/-/types-0.1.13.tgz";
        sha512 = "JL7eeCk6zWCbiYQg2xQSdLXQJl8Qoc9rXmG2cEKvHe3CKwMHwHGpfOb8frzNLmbycOo6I51qxnLnn9ESf4I20Q==";
      };
    };
    "@swc/wasm-1.7.42" = {
      name = "_at_swc_slash_wasm";
      packageName = "@swc/wasm";
      version = "1.7.42";
      src = fetchurl {
        url = "https://registry.npmjs.org/@swc/wasm/-/wasm-1.7.42.tgz";
        sha512 = "7/VWIYilY2uYQnwCrAJNAwgl0r+9Abhu1eVQ8lFA8hwj/Ls59Y46rzBWFxzstlaFDhGXYYRY3BtEsnjKSsyx2Q==";
      };
    };
    "@tailwindcss/typography-0.5.15" = {
      name = "_at_tailwindcss_slash_typography";
      packageName = "@tailwindcss/typography";
      version = "0.5.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tailwindcss/typography/-/typography-0.5.15.tgz";
        sha512 = "AqhlCXl+8grUz8uqExv5OTtgpjuVIwFTSXTrh8y9/pw6q2ek7fJ+Y8ZEVw7EB2DCcuCOtEjf9w3+J3rzts01uA==";
      };
    };
    "@trysound/sax-0.2.0" = {
      name = "_at_trysound_slash_sax";
      packageName = "@trysound/sax";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@trysound/sax/-/sax-0.2.0.tgz";
        sha512 = "L7z9BgrNEcYyUYtF+HaEfiS5ebkh9jXqbszz7pC0hRBPaatV0XjSD3+eHrpqFemQfgwiFF0QPIarnIihIDn7OA==";
      };
    };
    "@tsconfig/node10-1.0.11" = {
      name = "_at_tsconfig_slash_node10";
      packageName = "@tsconfig/node10";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tsconfig/node10/-/node10-1.0.11.tgz";
        sha512 = "DcRjDCujK/kCk/cUe8Xz8ZSpm8mS3mNNpta+jGCA6USEDfktlNvm1+IuZ9eTcDbNk41BHwpHHeW+N1lKCz4zOw==";
      };
    };
    "@tsconfig/node12-1.0.11" = {
      name = "_at_tsconfig_slash_node12";
      packageName = "@tsconfig/node12";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tsconfig/node12/-/node12-1.0.11.tgz";
        sha512 = "cqefuRsh12pWyGsIoBKJA9luFu3mRxCA+ORZvA4ktLSzIuCUtWVxGIuXigEwO5/ywWFMZ2QEGKWvkZG1zDMTag==";
      };
    };
    "@tsconfig/node14-1.0.3" = {
      name = "_at_tsconfig_slash_node14";
      packageName = "@tsconfig/node14";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tsconfig/node14/-/node14-1.0.3.tgz";
        sha512 = "ysT8mhdixWK6Hw3i1V2AeRqZ5WfXg1G43mqoYlM2nc6388Fq5jcXyr5mRsqViLx/GJYdoL0bfXD8nmF+Zn/Iow==";
      };
    };
    "@tsconfig/node16-1.0.4" = {
      name = "_at_tsconfig_slash_node16";
      packageName = "@tsconfig/node16";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tsconfig/node16/-/node16-1.0.4.tgz";
        sha512 = "vxhUy4J8lyeyinH7Azl1pdd43GJhZH/tP2weN8TntQblOY+A0XbT8DJk1/oCPuOOyg/Ja757rG0CgHcWC8OfMA==";
      };
    };
    "@types/estree-1.0.6" = {
      name = "_at_types_slash_estree";
      packageName = "@types/estree";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/estree/-/estree-1.0.6.tgz";
        sha512 = "AYnb1nQyY49te+VRAVgmzfcgjYS91mY5P0TKUDCLEM+gNnA+3T6rWITXRLYCpahpqSQbN5cE+gHpnPyXjHWxcw==";
      };
    };
    "@types/node-22.8.6" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "22.8.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-22.8.6.tgz";
        sha512 = "tosuJYKrIqjQIlVCM4PEGxOmyg3FCPa/fViuJChnGeEIhjA46oy8FMVoF9su1/v8PNs2a8Q0iFNyOx0uOF91nw==";
      };
    };
    "acorn-8.14.0" = {
      name = "acorn";
      packageName = "acorn";
      version = "8.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-8.14.0.tgz";
        sha512 = "cl669nCJTZBsL97OF4kUQm5g5hC2uihk0NxY3WENAC0TYdILVkAyHymAntgxGkl7K+t0cXIrH5siy5S4XkFycA==";
      };
    };
    "acorn-walk-8.3.4" = {
      name = "acorn-walk";
      packageName = "acorn-walk";
      version = "8.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn-walk/-/acorn-walk-8.3.4.tgz";
        sha512 = "ueEepnujpqee2o5aIYnvHU6C0A42MNdsIDeqy5BydrkuC5R1ZuUFnm27EeFJGoEHJQgn3uleRvmTXaJgfXbt4g==";
      };
    };
    "ansi-regex-5.0.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.1.tgz";
        sha512 = "quJQXlTSUGL2LH9SUXo8VwsY4soanhgo6LNSm84E1LBcE8s3O0wpdiRzyR9z/ZZJMlMWv37qOOb9pdJlMUEKFQ==";
      };
    };
    "ansi-regex-6.1.0" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-6.1.0.tgz";
        sha512 = "7HSX4QQb4CspciLpVFwyRe79O3xsIZDDLER21kERQ71oaPodF8jL725AgJMFAYbooIqolJoRLuM81SpeUkpkvA==";
      };
    };
    "ansi-styles-4.3.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
        sha512 = "zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
      };
    };
    "ansi-styles-6.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "6.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-6.2.1.tgz";
        sha512 = "bN798gFfQX+viw3R7yrGWRqnrN2oRkEkUjjl4JNn4E8GxxbjtG3FbrEIIY3l8/hrwUwIeCZvi4QuOTP4MErVug==";
      };
    };
    "any-promise-1.3.0" = {
      name = "any-promise";
      packageName = "any-promise";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/any-promise/-/any-promise-1.3.0.tgz";
        sha512 = "7UvmKalWRt1wgjL1RrGxoSJW/0QZFIegpeGvZG9kjp8vrRu55XTHbwnqq2GpXm9uLbcuhxm3IqX9OB4MZR1b2A==";
      };
    };
    "anymatch-3.1.3" = {
      name = "anymatch";
      packageName = "anymatch";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/anymatch/-/anymatch-3.1.3.tgz";
        sha512 = "KMReFUr0B4t+D+OBkjR3KYqvocp2XaSzO55UcB6mgQMd3KbcE+mWTyvVV7D/zsdEbNnV6acZUutkiHQXvTr1Rw==";
      };
    };
    "arg-4.1.3" = {
      name = "arg";
      packageName = "arg";
      version = "4.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/arg/-/arg-4.1.3.tgz";
        sha512 = "58S9QDqG0Xx27YwPSt9fJxivjYl432YCwfDMfZ+71RAqUrZef7LrKQZ3LHLOwCS4FLNBplP533Zx895SeOCHvA==";
      };
    };
    "arg-5.0.2" = {
      name = "arg";
      packageName = "arg";
      version = "5.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/arg/-/arg-5.0.2.tgz";
        sha512 = "PYjyFOLKQ9y57JvQ6QLo8dAgNqswh8M1RMJYdQduT6xbWSgK36P/Z/v+p888pM69jMMfS8Xd8F6I1kQ/I9HUGg==";
      };
    };
    "autoprefixer-10.4.20" = {
      name = "autoprefixer";
      packageName = "autoprefixer";
      version = "10.4.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/autoprefixer/-/autoprefixer-10.4.20.tgz";
        sha512 = "XY25y5xSv/wEoqzDyXXME4AFfkZI0P23z6Fs3YgymDnKJkCGOnkL0iTxCa85UTqaSgfcqyf3UA6+c7wUvx/16g==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "binary-extensions-2.3.0" = {
      name = "binary-extensions";
      packageName = "binary-extensions";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/binary-extensions/-/binary-extensions-2.3.0.tgz";
        sha512 = "Ceh+7ox5qe7LJuLHoY0feh3pHuUDHAcRUeyL2VYghZwfpkNIy/+8Ocg0a3UuSoYzavmylwuLWQOf3hl0jjMMIw==";
      };
    };
    "boolbase-1.0.0" = {
      name = "boolbase";
      packageName = "boolbase";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/boolbase/-/boolbase-1.0.0.tgz";
        sha512 = "JZOSA7Mo9sNGB8+UjSgzdLtokWAky1zbztM3WRLCbZ70/3cTANmQmOdR7y2g+J0e2WXywy1yS468tY+IruqEww==";
      };
    };
    "brace-expansion-2.0.1" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-2.0.1.tgz";
        sha512 = "XnAIvQ8eM+kC6aULx6wuQiwVsnzsi9d3WxzV3FpWTGA19F621kwdbsAcFKXgKUHZWsy+mY6iL1sHTxWEFCytDA==";
      };
    };
    "braces-3.0.3" = {
      name = "braces";
      packageName = "braces";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/braces/-/braces-3.0.3.tgz";
        sha512 = "yQbXgO/OSZVD2IsiLlro+7Hf6Q18EJrKSEsdoMzKePKXct3gvD8oLcOQdIzGupr5Fj+EDe8gO/lxc1BzfMpxvA==";
      };
    };
    "browserslist-4.24.2" = {
      name = "browserslist";
      packageName = "browserslist";
      version = "4.24.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserslist/-/browserslist-4.24.2.tgz";
        sha512 = "ZIc+Q62revdMcqC6aChtW4jz3My3klmCO1fEmINZY/8J3EpBg5/A/D0AKmBveUh6pgoeycoMkVMko84tuYS+Gg==";
      };
    };
    "buffer-from-1.1.2" = {
      name = "buffer-from";
      packageName = "buffer-from";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-from/-/buffer-from-1.1.2.tgz";
        sha512 = "E+XQCRwSbaaiChtv6k6Dwgc+bx+Bs6vuKJHHl5kox/BaKbhiXzqQOwK4cO22yElGp2OCmjwVhT3HmxgyPGnJfQ==";
      };
    };
    "camelcase-css-2.0.1" = {
      name = "camelcase-css";
      packageName = "camelcase-css";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/camelcase-css/-/camelcase-css-2.0.1.tgz";
        sha512 = "QOSvevhslijgYwRx6Rv7zKdMF8lbRmx+uQGx2+vDc+KI/eBnsy9kit5aj23AgGu3pa4t9AgwbnXWqS+iOY+2aA==";
      };
    };
    "caniuse-api-3.0.0" = {
      name = "caniuse-api";
      packageName = "caniuse-api";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caniuse-api/-/caniuse-api-3.0.0.tgz";
        sha512 = "bsTwuIg/BZZK/vreVTYYbSWoe2F+71P7K5QGEX+pT250DZbfU1MQ5prOKpPR+LL6uWKK3KMwMCAS74QB3Um1uw==";
      };
    };
    "caniuse-lite-1.0.30001676" = {
      name = "caniuse-lite";
      packageName = "caniuse-lite";
      version = "1.0.30001676";
      src = fetchurl {
        url = "https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30001676.tgz";
        sha512 = "Qz6zwGCiPghQXGJvgQAem79esjitvJ+CxSbSQkW9H/UX5hg8XM88d4lp2W+MEQ81j+Hip58Il+jGVdazk1z9cw==";
      };
    };
    "chalk-4.1.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-4.1.2.tgz";
        sha512 = "oKnbhFyRIXpUuez8iBMmyEa4nbj4IOQyuhc/wy9kY7/WVPcwIO9VA668Pu8RkO7+0G76SLROeyw9CpQ061i4mA==";
      };
    };
    "chokidar-3.6.0" = {
      name = "chokidar";
      packageName = "chokidar";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chokidar/-/chokidar-3.6.0.tgz";
        sha512 = "7VT13fmjotKpGipCW9JEQAusEPE+Ei8nl6/g4FBAmIm0GOOLMua9NDDo/DWp0ZAxCr3cPq5ZpBqmPAQgDda2Pw==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "colord-2.9.3" = {
      name = "colord";
      packageName = "colord";
      version = "2.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/colord/-/colord-2.9.3.tgz";
        sha512 = "jeC1axXpnb0/2nn/Y1LPuLdgXBLH7aDcHu4KEKfqw3CUhX7ZpfBSlPKyqXE6btIgEzfWtrX3/tyBCaCvXvMkOw==";
      };
    };
    "commander-2.20.3" = {
      name = "commander";
      packageName = "commander";
      version = "2.20.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.20.3.tgz";
        sha512 = "GpVkmM8vF2vQUkj2LvZmD35JxeJOLCwJ9cUkugyk2nuhbv3+mJvpLYYt+0+USMxE+oj+ey/lJEnhZw75x/OMcQ==";
      };
    };
    "commander-4.1.1" = {
      name = "commander";
      packageName = "commander";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-4.1.1.tgz";
        sha512 = "NOKm8xhkzAjzFx8B2v5OAHT+u5pRQc2UCa2Vq9jYL/31o2wi9mxBA7LIFs3sV5VSC49z6pEhfbMULvShKj26WA==";
      };
    };
    "commander-7.2.0" = {
      name = "commander";
      packageName = "commander";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-7.2.0.tgz";
        sha512 = "QrWXB+ZQSVPmIWIhtEO9H+gwHaMGYiF5ChvoJ+K9ZGHG/sVsa6yiesAD1GC/x46sET00Xlwo1u49RVVVzvcSkw==";
      };
    };
    "concat-with-sourcemaps-1.1.0" = {
      name = "concat-with-sourcemaps";
      packageName = "concat-with-sourcemaps";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-with-sourcemaps/-/concat-with-sourcemaps-1.1.0.tgz";
        sha512 = "4gEjHJFT9e+2W/77h/DS5SGUgwDaOwprX8L/gl5+3ixnzkVJJsZWDSelmN3Oilw3LNDZjZV0yqH1hLG3k6nghg==";
      };
    };
    "create-require-1.1.1" = {
      name = "create-require";
      packageName = "create-require";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-require/-/create-require-1.1.1.tgz";
        sha512 = "dcKFX3jn0MpIaXjisoRvexIJVEKzaq7z2rZKxf+MSr9TkdmHmsU4m2lcLojrj/FHl8mk5VxMmYA+ftRkP/3oKQ==";
      };
    };
    "cross-spawn-7.0.3" = {
      name = "cross-spawn";
      packageName = "cross-spawn";
      version = "7.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.3.tgz";
        sha512 = "iRDPJKUPVEND7dHPO8rkbOnPpyDygcDFtWjpeWNCgy8WP2rXcxXL8TskReQl6OrB2G7+UJrags1q15Fudc7G6w==";
      };
    };
    "css-declaration-sorter-6.4.1" = {
      name = "css-declaration-sorter";
      packageName = "css-declaration-sorter";
      version = "6.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-declaration-sorter/-/css-declaration-sorter-6.4.1.tgz";
        sha512 = "rtdthzxKuyq6IzqX6jEcIzQF/YqccluefyCYheovBOLhFT/drQA9zj/UbRAa9J7C0o6EG6u3E6g+vKkay7/k3g==";
      };
    };
    "css-select-4.3.0" = {
      name = "css-select";
      packageName = "css-select";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-select/-/css-select-4.3.0.tgz";
        sha512 = "wPpOYtnsVontu2mODhA19JrqWxNsfdatRKd64kmpRbQgh1KtItko5sTnEpPdpSaJszTOhEMlF/RPz28qj4HqhQ==";
      };
    };
    "css-tree-1.1.3" = {
      name = "css-tree";
      packageName = "css-tree";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-tree/-/css-tree-1.1.3.tgz";
        sha512 = "tRpdppF7TRazZrjJ6v3stzv93qxRcSsFmW6cX0Zm2NVKpxE1WV1HblnghVv9TreireHkqI/VDEsfolRF1p6y7Q==";
      };
    };
    "css-what-6.1.0" = {
      name = "css-what";
      packageName = "css-what";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-what/-/css-what-6.1.0.tgz";
        sha512 = "HTUrgRJ7r4dsZKU6GjmpfRK1O76h97Z8MfS1G0FozR+oF2kG6Vfe8JE6zwrkbxigziPHinCJ+gCPjA9EaBDtRw==";
      };
    };
    "cssesc-3.0.0" = {
      name = "cssesc";
      packageName = "cssesc";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssesc/-/cssesc-3.0.0.tgz";
        sha512 = "/Tb/JcjK111nNScGob5MNtsntNM1aCNUDipB/TkwZFhyDrrE47SOx/18wF2bbjgc3ZzCSKW1T5nt5EbFoAz/Vg==";
      };
    };
    "cssnano-5.1.15" = {
      name = "cssnano";
      packageName = "cssnano";
      version = "5.1.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssnano/-/cssnano-5.1.15.tgz";
        sha512 = "j+BKgDcLDQA+eDifLx0EO4XSA56b7uut3BQFH+wbSaSTuGLuiyTa/wbRYthUXX8LC9mLg+WWKe8h+qJuwTAbHw==";
      };
    };
    "cssnano-preset-default-5.2.14" = {
      name = "cssnano-preset-default";
      packageName = "cssnano-preset-default";
      version = "5.2.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssnano-preset-default/-/cssnano-preset-default-5.2.14.tgz";
        sha512 = "t0SFesj/ZV2OTylqQVOrFgEh5uanxbO6ZAdeCrNsUQ6fVuXwYTxJPNAGvGTxHbD68ldIJNec7PyYZDBrfDQ+6A==";
      };
    };
    "cssnano-utils-3.1.0" = {
      name = "cssnano-utils";
      packageName = "cssnano-utils";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssnano-utils/-/cssnano-utils-3.1.0.tgz";
        sha512 = "JQNR19/YZhz4psLX/rQ9M83e3z2Wf/HdJbryzte4a3NSuafyp9w/I4U+hx5C2S9g41qlstH7DEWnZaaj83OuEA==";
      };
    };
    "csso-4.2.0" = {
      name = "csso";
      packageName = "csso";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/csso/-/csso-4.2.0.tgz";
        sha512 = "wvlcdIbf6pwKEk7vHj8/Bkc0B4ylXZruLvOgs9doS5eOsOpuodOV2zJChSpkp+pRpYQLQMeF04nr3Z68Sta9jA==";
      };
    };
    "didyoumean-1.2.2" = {
      name = "didyoumean";
      packageName = "didyoumean";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/didyoumean/-/didyoumean-1.2.2.tgz";
        sha512 = "gxtyfqMg7GKyhQmb056K7M3xszy/myH8w+B4RT+QXBQsvAOdc3XymqDDPHx1BgPgsdAA5SIifona89YtRATDzw==";
      };
    };
    "diff-4.0.2" = {
      name = "diff";
      packageName = "diff";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/diff/-/diff-4.0.2.tgz";
        sha512 = "58lmxKSA4BNyLz+HHMUzlOEpg09FV+ev6ZMe3vJihgdxzgcwZ8VoEEPmALCZG9LmqfVoNMMKpttIYTVG6uDY7A==";
      };
    };
    "dlv-1.1.3" = {
      name = "dlv";
      packageName = "dlv";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/dlv/-/dlv-1.1.3.tgz";
        sha512 = "+HlytyjlPKnIG8XuRG8WvmBP8xs8P71y+SKKS6ZXWoEgLuePxtDoUEiH7WkdePWrQ5JBpE6aoVqfZfJUQkjXwA==";
      };
    };
    "dom-serializer-1.4.1" = {
      name = "dom-serializer";
      packageName = "dom-serializer";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-serializer/-/dom-serializer-1.4.1.tgz";
        sha512 = "VHwB3KfrcOOkelEG2ZOfxqLZdfkil8PtJi4P8N2MMXucZq2yLp75ClViUlOVwyoHEDjYU433Aq+5zWP61+RGag==";
      };
    };
    "domelementtype-2.3.0" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-2.3.0.tgz";
        sha512 = "OLETBj6w0OsagBwdXnPdN0cnMfF9opN69co+7ZrbfPGrdpPVNBUj02spi6B1N7wChLQiPn4CSH/zJvXw56gmHw==";
      };
    };
    "domhandler-4.3.1" = {
      name = "domhandler";
      packageName = "domhandler";
      version = "4.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/domhandler/-/domhandler-4.3.1.tgz";
        sha512 = "GrwoxYN+uWlzO8uhUXRl0P+kHE4GtVPfYzVLcUxPL7KNdHKj66vvlhiweIHqYYXWlw+T8iLMp42Lm67ghw4WMQ==";
      };
    };
    "domutils-2.8.0" = {
      name = "domutils";
      packageName = "domutils";
      version = "2.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domutils/-/domutils-2.8.0.tgz";
        sha512 = "w96Cjofp72M5IIhpjgobBimYEfoPjx1Vx0BSX9P30WBdZW2WIKU0T1Bd0kz2eNZ9ikjKgHbEyKx8BB6H1L3h3A==";
      };
    };
    "eastasianwidth-0.2.0" = {
      name = "eastasianwidth";
      packageName = "eastasianwidth";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/eastasianwidth/-/eastasianwidth-0.2.0.tgz";
        sha512 = "I88TYZWc9XiYHRQ4/3c5rjjfgkjhLyW2luGIheGERbNQ6OY7yTybanSpDXZa8y7VUP9YmDcYa+eyq4ca7iLqWA==";
      };
    };
    "electron-to-chromium-1.5.50" = {
      name = "electron-to-chromium";
      packageName = "electron-to-chromium";
      version = "1.5.50";
      src = fetchurl {
        url = "https://registry.npmjs.org/electron-to-chromium/-/electron-to-chromium-1.5.50.tgz";
        sha512 = "eMVObiUQ2LdgeO1F/ySTXsvqvxb6ZH2zPGaMYsWzRDdOddUa77tdmI0ltg+L16UpbWdhPmuF3wIQYyQq65WfZw==";
      };
    };
    "emoji-regex-8.0.0" = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-8.0.0.tgz";
        sha512 = "MSjYzcWNOA0ewAHpz0MxpYFvwg6yjy1NG3xteoqz644VCo/RPgnr1/GGt+ic3iJTzQ8Eu3TdM14SawnVUmGE6A==";
      };
    };
    "emoji-regex-9.2.2" = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "9.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-9.2.2.tgz";
        sha512 = "L18DaJsXSUk2+42pv8mLs5jJT2hqFkFE4j21wOmgbUqsZ2hL72NsUU785g9RXgo3s0ZNgVl42TiHp3ZtOv/Vyg==";
      };
    };
    "entities-2.2.0" = {
      name = "entities";
      packageName = "entities";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-2.2.0.tgz";
        sha512 = "p92if5Nz619I0w+akJrLZH0MX0Pb5DX39XOwQTtXSdQQOaYH03S1uIQp4mhOZtAXrxq4ViO67YTiLBo2638o9A==";
      };
    };
    "escalade-3.2.0" = {
      name = "escalade";
      packageName = "escalade";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escalade/-/escalade-3.2.0.tgz";
        sha512 = "WUj2qlxaQtO4g6Pq5c29GTcWGDyd8itL8zTlipgECz3JesAiiOKotd8JU6otB3PACgG6xkJUyVhboMS+bje/jA==";
      };
    };
    "estree-walker-0.6.1" = {
      name = "estree-walker";
      packageName = "estree-walker";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/estree-walker/-/estree-walker-0.6.1.tgz";
        sha512 = "SqmZANLWS0mnatqbSfRP5g8OXZC12Fgg1IwNtLsyHDzJizORW4khDfjPqJZsemPWBB2uqykUah5YpQ6epsqC/w==";
      };
    };
    "eventemitter3-4.0.7" = {
      name = "eventemitter3";
      packageName = "eventemitter3";
      version = "4.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/eventemitter3/-/eventemitter3-4.0.7.tgz";
        sha512 = "8guHBZCwKnFhYdHr2ysuRWErTwhoN2X8XELRlrRwpmfeY2jjuUN4taQMsULKUVo1K4DvZl+0pgfyoysHxvmvEw==";
      };
    };
    "fast-glob-3.3.2" = {
      name = "fast-glob";
      packageName = "fast-glob";
      version = "3.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-glob/-/fast-glob-3.3.2.tgz";
        sha512 = "oX2ruAFQwf/Orj8m737Y5adxDQO0LAB7/S5MnxCdTNDd4p6BsyIVsv9JQsATbTSq8KHRpLwIHbVlUNatxd+1Ow==";
      };
    };
    "fastq-1.17.1" = {
      name = "fastq";
      packageName = "fastq";
      version = "1.17.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fastq/-/fastq-1.17.1.tgz";
        sha512 = "sRVD3lWVIXWg6By68ZN7vho9a1pQcN/WBFaAAsDDFzlJjvoGx0P8z7V1t72grFJfJhu3YPZBuu25f7Kaw2jN1w==";
      };
    };
    "fill-range-7.1.1" = {
      name = "fill-range";
      packageName = "fill-range";
      version = "7.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fill-range/-/fill-range-7.1.1.tgz";
        sha512 = "YsGpe3WHLK8ZYi4tWDg2Jy3ebRz2rXowDxnld4bkQB00cc/1Zw9AWnC0i9ztDJitivtQvaI9KaLyKrc+hBW0yg==";
      };
    };
    "foreground-child-3.3.0" = {
      name = "foreground-child";
      packageName = "foreground-child";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/foreground-child/-/foreground-child-3.3.0.tgz";
        sha512 = "Ld2g8rrAyMYFXBhEqMz8ZAHBi4J4uS1i/CxGMDnjyFWddMXLVcDp051DZfu+t7+ab7Wv6SMqpWmyFIj5UbfFvg==";
      };
    };
    "fraction.js-4.3.7" = {
      name = "fraction.js";
      packageName = "fraction.js";
      version = "4.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/fraction.js/-/fraction.js-4.3.7.tgz";
        sha512 = "ZsDfxO51wGAXREY55a7la9LScWpwv9RxIrYABrlvOFBlH/ShPnrtsXeuUIfXKKOVicNxQ+o8JTbJvjS4M89yew==";
      };
    };
    "function-bind-1.1.2" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.2.tgz";
        sha512 = "7XHNxH7qX9xG5mIwxkhumTox/MIRNcOgDrxWsMt2pAr23WHp6MrRlN7FBSFpCpr+oVO0F744iUgR82nJMfG2SA==";
      };
    };
    "generic-names-4.0.0" = {
      name = "generic-names";
      packageName = "generic-names";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/generic-names/-/generic-names-4.0.0.tgz";
        sha512 = "ySFolZQfw9FoDb3ed9d80Cm9f0+r7qj+HJkWjeD9RBfpxEVTlVhol+gvaQB/78WbwYfbnNh8nWHHBSlg072y6A==";
      };
    };
    "glob-10.4.5" = {
      name = "glob";
      packageName = "glob";
      version = "10.4.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-10.4.5.tgz";
        sha512 = "7Bv8RF0k6xjo7d4A/PxYLbUCfb6c+Vpd2/mB2yRDlew7Jb5hEXiCD9ibfO7wpk8i4sevK6DFny9h7EYbM3/sHg==";
      };
    };
    "glob-parent-5.1.2" = {
      name = "glob-parent";
      packageName = "glob-parent";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-parent/-/glob-parent-5.1.2.tgz";
        sha512 = "AOIgSQCepiJYwP3ARnGx+5VnTu2HBYdzbGP45eLw1vr3zB3vZLeyed1sC9hnbcOc9/SrMyM5RPQrkGz4aS9Zow==";
      };
    };
    "glob-parent-6.0.2" = {
      name = "glob-parent";
      packageName = "glob-parent";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-parent/-/glob-parent-6.0.2.tgz";
        sha512 = "XxwI8EOhVQgWp6iDL+3b0r86f4d6AX6zSU55HfB4ydCEuXLXc5FcYeOu+nnGftS4TEju/11rt4KJPTMgbfmv4A==";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "hasown-2.0.2" = {
      name = "hasown";
      packageName = "hasown";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hasown/-/hasown-2.0.2.tgz";
        sha512 = "0hJU9SCPvmMzIBdZFqNPXWa6dqh7WdH0cII9y+CyS8rG3nL48Bclra9HmKhVVUHyPWNH5Y7xDwAB7bfgSjkUMQ==";
      };
    };
    "icss-replace-symbols-1.1.0" = {
      name = "icss-replace-symbols";
      packageName = "icss-replace-symbols";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/icss-replace-symbols/-/icss-replace-symbols-1.1.0.tgz";
        sha512 = "chIaY3Vh2mh2Q3RGXttaDIzeiPvaVXJ+C4DAh/w3c37SKZ/U6PGMmuicR2EQQp9bKG8zLMCl7I+PtIoOOPp8Gg==";
      };
    };
    "icss-utils-5.1.0" = {
      name = "icss-utils";
      packageName = "icss-utils";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/icss-utils/-/icss-utils-5.1.0.tgz";
        sha512 = "soFhflCVWLfRNOPU3iv5Z9VUdT44xFRbzjLsEzSr5AQmgqPMTHdU3PMT1Cf1ssx8fLNJDA1juftYl+PUcv3MqA==";
      };
    };
    "import-cwd-3.0.0" = {
      name = "import-cwd";
      packageName = "import-cwd";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/import-cwd/-/import-cwd-3.0.0.tgz";
        sha512 = "4pnzH16plW+hgvRECbDWpQl3cqtvSofHWh44met7ESfZ8UZOWWddm8hEyDTqREJ9RbYHY8gi8DqmaelApoOGMg==";
      };
    };
    "import-from-3.0.0" = {
      name = "import-from";
      packageName = "import-from";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/import-from/-/import-from-3.0.0.tgz";
        sha512 = "CiuXOFFSzkU5x/CR0+z7T91Iht4CXgfCxVOFRhh2Zyhg5wOpWvvDLQUsWl+gcN+QscYBjez8hDCt85O7RLDttQ==";
      };
    };
    "is-binary-path-2.1.0" = {
      name = "is-binary-path";
      packageName = "is-binary-path";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-binary-path/-/is-binary-path-2.1.0.tgz";
        sha512 = "ZMERYes6pDydyuGidse7OsHxtbI7WVeUEozgR/g7rd0xUimYNlvZRE/K2MgZTjWy725IfelLeVcEM97mmtRGXw==";
      };
    };
    "is-core-module-2.15.1" = {
      name = "is-core-module";
      packageName = "is-core-module";
      version = "2.15.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-core-module/-/is-core-module-2.15.1.tgz";
        sha512 = "z0vtXSwucUJtANQWldhbtbt7BnL0vxiFjIdDLAatwhDYty2bad6s+rijD6Ri4YuYJubLzIJLUidCh09e1djEVQ==";
      };
    };
    "is-extglob-2.1.1" = {
      name = "is-extglob";
      packageName = "is-extglob";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extglob/-/is-extglob-2.1.1.tgz";
        sha512 = "SbKbANkN603Vi4jEZv49LeVJMn4yGwsbzZworEoyEiutsN3nJYdbO36zfhGJ6QEDpOZIFkDtnq5JRxmvl3jsoQ==";
      };
    };
    "is-fullwidth-code-point-3.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz";
        sha512 = "zymm5+u+sCsSWyD9qNaejV3DFvhCKclKdizYaJUuHA83RLjb7nSuGnddCHGv0hk+KY7BMAlsWeK4Ueg6EV6XQg==";
      };
    };
    "is-glob-4.0.3" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-4.0.3.tgz";
        sha512 = "xelSayHH36ZgE7ZWhli7pW34hNbNl8Ojv5KVmkJD4hBdD3th8Tfk9vYasLM+mXWOZhFkgZfxhLSnrwRr4elSSg==";
      };
    };
    "is-number-7.0.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-7.0.0.tgz";
        sha512 = "41Cifkg6e8TylSpdtTpeLVMqvSBEVzTttHvERD741+pnZ8ANv0004MRL43QKPDlK9cGvNp6NZWZUBlbGXYxxng==";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha512 = "RHxMLp9lnKHGHRng9QFhRCMbYAcVpn69smSGcq3f36xjgVVWThj4qqLbTLlq7Ssj8B+fIQ1EuCEGI2lKsyQeIw==";
      };
    };
    "jackspeak-3.4.3" = {
      name = "jackspeak";
      packageName = "jackspeak";
      version = "3.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/jackspeak/-/jackspeak-3.4.3.tgz";
        sha512 = "OGlZQpz2yfahA/Rd1Y8Cd9SIEsqvXkLVoSw/cgwhnhFMDbsQFeZYoJJ7bIZBS9BcamUW96asq/npPWugM+RQBw==";
      };
    };
    "jiti-1.21.6" = {
      name = "jiti";
      packageName = "jiti";
      version = "1.21.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/jiti/-/jiti-1.21.6.tgz";
        sha512 = "2yTgeWTWzMWkHu6Jp9NKgePDaYHbntiwvYuuJLbbN9vl7DC9DvXKOB2BC3ZZ92D3cvV/aflH0osDfwpHepQ53w==";
      };
    };
    "lilconfig-2.1.0" = {
      name = "lilconfig";
      packageName = "lilconfig";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lilconfig/-/lilconfig-2.1.0.tgz";
        sha512 = "utWOt/GHzuUxnLKxB6dk81RoOeoNeHgbrXiuGk4yyF5qlRz+iIVWu56E2fqGHFrXz0QNUhLB/8nKqvRH66JKGQ==";
      };
    };
    "lilconfig-3.1.2" = {
      name = "lilconfig";
      packageName = "lilconfig";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lilconfig/-/lilconfig-3.1.2.tgz";
        sha512 = "eop+wDAvpItUys0FWkHIKeC9ybYrTGbU41U5K7+bttZZeohvnY7M9dZ5kB21GNWiFT2q1OoPTvncPCgSOVO5ow==";
      };
    };
    "lines-and-columns-1.2.4" = {
      name = "lines-and-columns";
      packageName = "lines-and-columns";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lines-and-columns/-/lines-and-columns-1.2.4.tgz";
        sha512 = "7ylylesZQ/PV29jhEDl3Ufjo6ZX7gCqJr5F7PKrqc93v7fzSymt1BpwEU8nAUXs8qzzvqhbjhK5QZg6Mt/HkBg==";
      };
    };
    "loader-utils-3.3.1" = {
      name = "loader-utils";
      packageName = "loader-utils";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/loader-utils/-/loader-utils-3.3.1.tgz";
        sha512 = "FMJTLMXfCLMLfJxcX9PFqX5qD88Z5MRGaZCVzfuqeZSPsyiBzs+pahDQjbIWz2QIzPZz0NX9Zy4FX3lmK6YHIg==";
      };
    };
    "lodash.camelcase-4.3.0" = {
      name = "lodash.camelcase";
      packageName = "lodash.camelcase";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.camelcase/-/lodash.camelcase-4.3.0.tgz";
        sha512 = "TwuEnCnxbc3rAvhf/LbG7tJUDzhqXyFnv3dtzLOPgCG/hODL7WFnsbwktkD7yUV0RrreP/l1PALq/YSg6VvjlA==";
      };
    };
    "lodash.castarray-4.4.0" = {
      name = "lodash.castarray";
      packageName = "lodash.castarray";
      version = "4.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.castarray/-/lodash.castarray-4.4.0.tgz";
        sha512 = "aVx8ztPv7/2ULbArGJ2Y42bG1mEQ5mGjpdvrbJcJFU3TbYybe+QlLS4pst9zV52ymy2in1KpFPiZnAOATxD4+Q==";
      };
    };
    "lodash.isplainobject-4.0.6" = {
      name = "lodash.isplainobject";
      packageName = "lodash.isplainobject";
      version = "4.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isplainobject/-/lodash.isplainobject-4.0.6.tgz";
        sha512 = "oSXzaWypCMHkPC3NvBEaPHf0KsA5mvPrOPgQWDsbg8n7orZ290M0BmC/jgRZ4vcJ6DTAhjrsSYgdsW/F+MFOBA==";
      };
    };
    "lodash.memoize-4.1.2" = {
      name = "lodash.memoize";
      packageName = "lodash.memoize";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.memoize/-/lodash.memoize-4.1.2.tgz";
        sha512 = "t7j+NzmgnQzTAYXcsHYLgimltOV1MXHtlOWf6GjL9Kj8GK5FInw5JotxvbOs+IvV1/Dzo04/fCGfLVs7aXb4Ag==";
      };
    };
    "lodash.merge-4.6.2" = {
      name = "lodash.merge";
      packageName = "lodash.merge";
      version = "4.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.merge/-/lodash.merge-4.6.2.tgz";
        sha512 = "0KpjqXRVvrYyCsX1swR/XTK0va6VQkQM6MNo7PqW77ByjAhoARA8EfrP1N4+KlKj8YS0ZUCtRT/YUuhyYDujIQ==";
      };
    };
    "lodash.uniq-4.5.0" = {
      name = "lodash.uniq";
      packageName = "lodash.uniq";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.uniq/-/lodash.uniq-4.5.0.tgz";
        sha512 = "xfBaXQd9ryd9dlSDvnvI0lvxfLJlYAZzXomUYzLKtUeOQvOP5piqAWuGtrhWeqaXK9hhoM/iyJc5AV+XfsX3HQ==";
      };
    };
    "lru-cache-10.4.3" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "10.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-10.4.3.tgz";
        sha512 = "JNAzZcXrCt42VGLuYz0zfAzDfAvJWW6AfYlDBQyDV5DClI2m5sAmK+OIO7s59XfsRsWHp02jAJrRadPRGTt6SQ==";
      };
    };
    "make-error-1.3.6" = {
      name = "make-error";
      packageName = "make-error";
      version = "1.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/make-error/-/make-error-1.3.6.tgz";
        sha512 = "s8UhlNe7vPKomQhC1qFelMokr/Sc3AgNbso3n74mVPA5LTZwkB9NlXf4XPamLxJE8h0gh73rM94xvwRT2CVInw==";
      };
    };
    "mdn-data-2.0.14" = {
      name = "mdn-data";
      packageName = "mdn-data";
      version = "2.0.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdn-data/-/mdn-data-2.0.14.tgz";
        sha512 = "dn6wd0uw5GsdswPFfsgMp5NSB0/aDe6fK94YJV/AJDYXL6HVLWBsxeq7js7Ad+mU2K9LAlwpk6kN2D5mwCPVow==";
      };
    };
    "merge2-1.4.1" = {
      name = "merge2";
      packageName = "merge2";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge2/-/merge2-1.4.1.tgz";
        sha512 = "8q7VEgMJW4J8tcfVPy8g09NcQwZdbwFEqhe/WZkoIzjn/3TGDwtOCYtXGxA3O8tPzpczCCDgv+P2P5y00ZJOOg==";
      };
    };
    "micromatch-4.0.8" = {
      name = "micromatch";
      packageName = "micromatch";
      version = "4.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromatch/-/micromatch-4.0.8.tgz";
        sha512 = "PXwfBhYu0hBCPw8Dn0E+WDYb7af3dSLVWKi3HGv84IdF4TyFoC0ysxFd0Goxw7nSv4T/PzEJQxsYsEiFCKo2BA==";
      };
    };
    "minimatch-9.0.5" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "9.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-9.0.5.tgz";
        sha512 = "G6T0ZX48xgozx7587koeX9Ys2NYy6Gmv//P89sEte9V9whIapMNF4idKxnW2QtCcLiTWlb/wfCabAtAFWhhBow==";
      };
    };
    "minipass-7.1.2" = {
      name = "minipass";
      packageName = "minipass";
      version = "7.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/minipass/-/minipass-7.1.2.tgz";
        sha512 = "qOOzS1cBTWYF4BH8fVePDBOO9iptMnGUEZwNc/cMWnTV2nVLZ7VoNWEPHkYczZA0pdoA7dl6e7FL659nX9S2aw==";
      };
    };
    "mz-2.7.0" = {
      name = "mz";
      packageName = "mz";
      version = "2.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mz/-/mz-2.7.0.tgz";
        sha512 = "z81GNO7nnYMEhrGh9LeymoE4+Yr0Wn5McHIZMK5cfQCl+NDX08sCZgUc9/6MHni9IWuFLm1Z3HTCXu2z9fN62Q==";
      };
    };
    "nanoid-3.3.7" = {
      name = "nanoid";
      packageName = "nanoid";
      version = "3.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoid/-/nanoid-3.3.7.tgz";
        sha512 = "eSRppjcPIatRIMC1U6UngP8XFcz8MQWGQdt1MTBQ7NaAmvXDfvNxbvWV3x2y6CdEUciCSsDHDQZbhYaB8QEo2g==";
      };
    };
    "node-releases-2.0.18" = {
      name = "node-releases";
      packageName = "node-releases";
      version = "2.0.18";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-releases/-/node-releases-2.0.18.tgz";
        sha512 = "d9VeXT4SJ7ZeOqGX6R5EM022wpL+eWPooLI+5UpWn2jCT1aosUQEhQP214x33Wkwx3JQMvIm+tIoVOdodFS40g==";
      };
    };
    "normalize-path-3.0.0" = {
      name = "normalize-path";
      packageName = "normalize-path";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-path/-/normalize-path-3.0.0.tgz";
        sha512 = "6eZs5Ls3WtCisHWp9S2GUy8dqkpGi4BVSz3GaqiE6ezub0512ESztXUwUB6C6IKbQkY2Pnb/mD4WYojCRwcwLA==";
      };
    };
    "normalize-range-0.1.2" = {
      name = "normalize-range";
      packageName = "normalize-range";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-range/-/normalize-range-0.1.2.tgz";
        sha512 = "bdok/XvKII3nUpklnV6P2hxtMNrCboOjAcyBuQnWEhO665FwrSNRxU+AqpsyvO6LgGYPspN+lu5CLtw4jPRKNA==";
      };
    };
    "normalize-url-6.1.0" = {
      name = "normalize-url";
      packageName = "normalize-url";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-url/-/normalize-url-6.1.0.tgz";
        sha512 = "DlL+XwOy3NxAQ8xuC0okPgK46iuVNAK01YN7RueYBqqFeGsBjV9XmCAzAdgt+667bCl5kPh9EqKKDwnaPG1I7A==";
      };
    };
    "nth-check-2.1.1" = {
      name = "nth-check";
      packageName = "nth-check";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/nth-check/-/nth-check-2.1.1.tgz";
        sha512 = "lqjrjmaOoAnWfMmBPL+XNnynZh2+swxiX3WUE0s4yEHI6m+AwrK2UZOimIRl3X/4QctVqS8AiZjFqyOGrMXb/w==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha512 = "rJgTQnkUnH1sFw8yT6VSU3zD3sWmu6sZhIseY8VX+GRu3P6F7Fu+JNDoXfklElbLJSnc3FUQHVe4cU5hj+BcUg==";
      };
    };
    "object-hash-3.0.0" = {
      name = "object-hash";
      packageName = "object-hash";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-hash/-/object-hash-3.0.0.tgz";
        sha512 = "RSn9F68PjH9HqtltsSnqYC1XXoWe9Bju5+213R98cNGttag9q9yAOTzdbsqvIa7aNm5WffBZFpWYr2aWrklWAw==";
      };
    };
    "p-finally-1.0.0" = {
      name = "p-finally";
      packageName = "p-finally";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-finally/-/p-finally-1.0.0.tgz";
        sha512 = "LICb2p9CB7FS+0eR1oqWnHhp0FljGLZCWBE9aix0Uye9W8LTQPwMTYVGWQWIw9RdQiDg4+epXQODwIYJtSJaow==";
      };
    };
    "p-queue-6.6.2" = {
      name = "p-queue";
      packageName = "p-queue";
      version = "6.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-queue/-/p-queue-6.6.2.tgz";
        sha512 = "RwFpb72c/BhQLEXIZ5K2e+AhgNVmIejGlTgiB9MzZ0e93GRvqZ7uSi0dvRF7/XIXDeNkra2fNHBxTyPDGySpjQ==";
      };
    };
    "p-timeout-3.2.0" = {
      name = "p-timeout";
      packageName = "p-timeout";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-timeout/-/p-timeout-3.2.0.tgz";
        sha512 = "rhIwUycgwwKcP9yTOOFK/AKsAopjjCakVqLHePO3CC6Mir1Z99xT+R63jZxAT5lFZLa2inS5h+ZS2GvR99/FBg==";
      };
    };
    "package-json-from-dist-1.0.1" = {
      name = "package-json-from-dist";
      packageName = "package-json-from-dist";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/package-json-from-dist/-/package-json-from-dist-1.0.1.tgz";
        sha512 = "UEZIS3/by4OC8vL3P2dTXRETpebLI2NiI5vIrjaD/5UtrkFX/tNbwjTSRAGC/+7CAo2pIcBaRgWmcBBHcsaCIw==";
      };
    };
    "path-key-3.1.1" = {
      name = "path-key";
      packageName = "path-key";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-key/-/path-key-3.1.1.tgz";
        sha512 = "ojmeN0qd+y0jszEtoY48r0Peq5dwMEkIlCOu6Q5f41lfkswXuKtYrhgoTpLnyIcHm24Uhqx+5Tqm2InSwLhE6Q==";
      };
    };
    "path-parse-1.0.7" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.7.tgz";
        sha512 = "LDJzPVEEEPR+y48z93A0Ed0yXb8pAByGWo/k5YYdYgpY2/2EsOsksJrq7lOHxryrVOn1ejG6oAp8ahvOIQD8sw==";
      };
    };
    "path-scurry-1.11.1" = {
      name = "path-scurry";
      packageName = "path-scurry";
      version = "1.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-scurry/-/path-scurry-1.11.1.tgz";
        sha512 = "Xa4Nw17FS9ApQFJ9umLiJS4orGjm7ZzwUrwamcGQuHSzDyth9boKDaycYdDcZDuqYATXw4HFXgaqWTctW/v1HA==";
      };
    };
    "picocolors-1.1.1" = {
      name = "picocolors";
      packageName = "picocolors";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/picocolors/-/picocolors-1.1.1.tgz";
        sha512 = "xceH2snhtb5M9liqDsmEw56le376mTZkEX/jEb/RxNFyegNul7eNslCXP9FDj/Lcu0X8KEyMceP2ntpaHrDEVA==";
      };
    };
    "picomatch-2.3.1" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-2.3.1.tgz";
        sha512 = "JU3teHTNjmE2VCGFzuY8EXzCDVwEqB2a8fsIvwaStHhAWJEeVd1o1QD80CU6+ZdEXXSLbSsuLwJjkCBWqRQUVA==";
      };
    };
    "pify-2.3.0" = {
      name = "pify";
      packageName = "pify";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pify/-/pify-2.3.0.tgz";
        sha512 = "udgsAY+fTnvv7kI7aaxbqwWNb0AHiB0qBO89PZKPkoTmGOgdbrHDKD+0B2X4uTfJ/FT1R09r9gTsjUjNJotuog==";
      };
    };
    "pify-5.0.0" = {
      name = "pify";
      packageName = "pify";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pify/-/pify-5.0.0.tgz";
        sha512 = "eW/gHNMlxdSP6dmG6uJip6FXN0EQBwm2clYYd8Wul42Cwu/DK8HEftzsapcNdYe2MfLiIwZqsDk2RDEsTE79hA==";
      };
    };
    "pirates-4.0.6" = {
      name = "pirates";
      packageName = "pirates";
      version = "4.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/pirates/-/pirates-4.0.6.tgz";
        sha512 = "saLsH7WeYYPiD25LDuLRRY/i+6HaPYr6G1OUlN39otzkSTxKnubR9RTxS3/Kk50s1g2JTgFwWQDQyplC5/SHZg==";
      };
    };
    "postcss-8.4.47" = {
      name = "postcss";
      packageName = "postcss";
      version = "8.4.47";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss/-/postcss-8.4.47.tgz";
        sha512 = "56rxCq7G/XfB4EkXq9Egn5GCqugWvDFjafDOThIdMBsI15iqPqR5r15TfSr1YPYeEI19YeaXMCbY6u88Y76GLQ==";
      };
    };
    "postcss-calc-8.2.4" = {
      name = "postcss-calc";
      packageName = "postcss-calc";
      version = "8.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-calc/-/postcss-calc-8.2.4.tgz";
        sha512 = "SmWMSJmB8MRnnULldx0lQIyhSNvuDl9HfrZkaqqE/WHAhToYsAvDq+yAsA/kIyINDszOp3Rh0GFoNuH5Ypsm3Q==";
      };
    };
    "postcss-colormin-5.3.1" = {
      name = "postcss-colormin";
      packageName = "postcss-colormin";
      version = "5.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-colormin/-/postcss-colormin-5.3.1.tgz";
        sha512 = "UsWQG0AqTFQmpBegeLLc1+c3jIqBNB0zlDGRWR+dQ3pRKJL1oeMzyqmH3o2PIfn9MBdNrVPWhDbT769LxCTLJQ==";
      };
    };
    "postcss-convert-values-5.1.3" = {
      name = "postcss-convert-values";
      packageName = "postcss-convert-values";
      version = "5.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-convert-values/-/postcss-convert-values-5.1.3.tgz";
        sha512 = "82pC1xkJZtcJEfiLw6UXnXVXScgtBrjlO5CBmuDQc+dlb88ZYheFsjTn40+zBVi3DkfF7iezO0nJUPLcJK3pvA==";
      };
    };
    "postcss-discard-comments-5.1.2" = {
      name = "postcss-discard-comments";
      packageName = "postcss-discard-comments";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-discard-comments/-/postcss-discard-comments-5.1.2.tgz";
        sha512 = "+L8208OVbHVF2UQf1iDmRcbdjJkuBF6IS29yBDSiWUIzpYaAhtNl6JYnYm12FnkeCwQqF5LeklOu6rAqgfBZqQ==";
      };
    };
    "postcss-discard-duplicates-5.1.0" = {
      name = "postcss-discard-duplicates";
      packageName = "postcss-discard-duplicates";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-discard-duplicates/-/postcss-discard-duplicates-5.1.0.tgz";
        sha512 = "zmX3IoSI2aoenxHV6C7plngHWWhUOV3sP1T8y2ifzxzbtnuhk1EdPwm0S1bIUNaJ2eNbWeGLEwzw8huPD67aQw==";
      };
    };
    "postcss-discard-empty-5.1.1" = {
      name = "postcss-discard-empty";
      packageName = "postcss-discard-empty";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-discard-empty/-/postcss-discard-empty-5.1.1.tgz";
        sha512 = "zPz4WljiSuLWsI0ir4Mcnr4qQQ5e1Ukc3i7UfE2XcrwKK2LIPIqE5jxMRxO6GbI3cv//ztXDsXwEWT3BHOGh3A==";
      };
    };
    "postcss-discard-overridden-5.1.0" = {
      name = "postcss-discard-overridden";
      packageName = "postcss-discard-overridden";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-discard-overridden/-/postcss-discard-overridden-5.1.0.tgz";
        sha512 = "21nOL7RqWR1kasIVdKs8HNqQJhFxLsyRfAnUDm4Fe4t4mCWL9OJiHvlHPjcd8zc5Myu89b/7wZDnOSjFgeWRtw==";
      };
    };
    "postcss-import-15.1.0" = {
      name = "postcss-import";
      packageName = "postcss-import";
      version = "15.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-import/-/postcss-import-15.1.0.tgz";
        sha512 = "hpr+J05B2FVYUAXHeK1YyI267J/dDDhMU6B6civm8hSY1jYJnBXxzKDKDswzJmtLHryrjhnDjqqp/49t8FALew==";
      };
    };
    "postcss-js-4.0.1" = {
      name = "postcss-js";
      packageName = "postcss-js";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-js/-/postcss-js-4.0.1.tgz";
        sha512 = "dDLF8pEO191hJMtlHFPRa8xsizHaM82MLfNkUHdUtVEV3tgTp5oj+8qbEqYM57SLfc74KSbw//4SeJma2LRVIw==";
      };
    };
    "postcss-load-config-3.1.4" = {
      name = "postcss-load-config";
      packageName = "postcss-load-config";
      version = "3.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-load-config/-/postcss-load-config-3.1.4.tgz";
        sha512 = "6DiM4E7v4coTE4uzA8U//WhtPwyhiim3eyjEMFCnUpzbrkK9wJHgKDT2mR+HbtSrd/NubVaYTOpSpjUl8NQeRg==";
      };
    };
    "postcss-load-config-4.0.2" = {
      name = "postcss-load-config";
      packageName = "postcss-load-config";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-load-config/-/postcss-load-config-4.0.2.tgz";
        sha512 = "bSVhyJGL00wMVoPUzAVAnbEoWyqRxkjv64tUl427SKnPrENtq6hJwUojroMz2VB+Q1edmi4IfrAPpami5VVgMQ==";
      };
    };
    "postcss-merge-longhand-5.1.7" = {
      name = "postcss-merge-longhand";
      packageName = "postcss-merge-longhand";
      version = "5.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-merge-longhand/-/postcss-merge-longhand-5.1.7.tgz";
        sha512 = "YCI9gZB+PLNskrK0BB3/2OzPnGhPkBEwmwhfYk1ilBHYVAZB7/tkTHFBAnCrvBBOmeYyMYw3DMjT55SyxMBzjQ==";
      };
    };
    "postcss-merge-rules-5.1.4" = {
      name = "postcss-merge-rules";
      packageName = "postcss-merge-rules";
      version = "5.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-merge-rules/-/postcss-merge-rules-5.1.4.tgz";
        sha512 = "0R2IuYpgU93y9lhVbO/OylTtKMVcHb67zjWIfCiKR9rWL3GUk1677LAqD/BcHizukdZEjT8Ru3oHRoAYoJy44g==";
      };
    };
    "postcss-minify-1.1.0" = {
      name = "postcss-minify";
      packageName = "postcss-minify";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-minify/-/postcss-minify-1.1.0.tgz";
        sha512 = "9D64ueIW0DL2FdLajQTlXrnTN8Ox9NjuXqigKMmB819RhdClNPYx5Zp3i5x0ghjjy3vGrLBBYEYvJjY/1eMNbw==";
      };
    };
    "postcss-minify-font-values-5.1.0" = {
      name = "postcss-minify-font-values";
      packageName = "postcss-minify-font-values";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-minify-font-values/-/postcss-minify-font-values-5.1.0.tgz";
        sha512 = "el3mYTgx13ZAPPirSVsHqFzl+BBBDrXvbySvPGFnQcTI4iNslrPaFq4muTkLZmKlGk4gyFAYUBMH30+HurREyA==";
      };
    };
    "postcss-minify-gradients-5.1.1" = {
      name = "postcss-minify-gradients";
      packageName = "postcss-minify-gradients";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-minify-gradients/-/postcss-minify-gradients-5.1.1.tgz";
        sha512 = "VGvXMTpCEo4qHTNSa9A0a3D+dxGFZCYwR6Jokk+/3oB6flu2/PnPXAh2x7x52EkY5xlIHLm+Le8tJxe/7TNhzw==";
      };
    };
    "postcss-minify-params-5.1.4" = {
      name = "postcss-minify-params";
      packageName = "postcss-minify-params";
      version = "5.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-minify-params/-/postcss-minify-params-5.1.4.tgz";
        sha512 = "+mePA3MgdmVmv6g+30rn57USjOGSAyuxUmkfiWpzalZ8aiBkdPYjXWtHuwJGm1v5Ojy0Z0LaSYhHaLJQB0P8Jw==";
      };
    };
    "postcss-minify-selectors-5.2.1" = {
      name = "postcss-minify-selectors";
      packageName = "postcss-minify-selectors";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-minify-selectors/-/postcss-minify-selectors-5.2.1.tgz";
        sha512 = "nPJu7OjZJTsVUmPdm2TcaiohIwxP+v8ha9NehQ2ye9szv4orirRU3SDdtUmKH+10nzn0bAyOXZ0UEr7OpvLehg==";
      };
    };
    "postcss-modules-4.3.1" = {
      name = "postcss-modules";
      packageName = "postcss-modules";
      version = "4.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-modules/-/postcss-modules-4.3.1.tgz";
        sha512 = "ItUhSUxBBdNamkT3KzIZwYNNRFKmkJrofvC2nWab3CPKhYBQ1f27XXh1PAPE27Psx58jeelPsxWB/+og+KEH0Q==";
      };
    };
    "postcss-modules-extract-imports-3.1.0" = {
      name = "postcss-modules-extract-imports";
      packageName = "postcss-modules-extract-imports";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-modules-extract-imports/-/postcss-modules-extract-imports-3.1.0.tgz";
        sha512 = "k3kNe0aNFQDAZGbin48pL2VNidTF0w4/eASDsxlyspobzU3wZQLOGj7L9gfRe0Jo9/4uud09DsjFNH7winGv8Q==";
      };
    };
    "postcss-modules-local-by-default-4.0.5" = {
      name = "postcss-modules-local-by-default";
      packageName = "postcss-modules-local-by-default";
      version = "4.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-modules-local-by-default/-/postcss-modules-local-by-default-4.0.5.tgz";
        sha512 = "6MieY7sIfTK0hYfafw1OMEG+2bg8Q1ocHCpoWLqOKj3JXlKu4G7btkmM/B7lFubYkYWmRSPLZi5chid63ZaZYw==";
      };
    };
    "postcss-modules-scope-3.2.0" = {
      name = "postcss-modules-scope";
      packageName = "postcss-modules-scope";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-modules-scope/-/postcss-modules-scope-3.2.0.tgz";
        sha512 = "oq+g1ssrsZOsx9M96c5w8laRmvEu9C3adDSjI8oTcbfkrTE8hx/zfyobUoWIxaKPO8bt6S62kxpw5GqypEw1QQ==";
      };
    };
    "postcss-modules-values-4.0.0" = {
      name = "postcss-modules-values";
      packageName = "postcss-modules-values";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-modules-values/-/postcss-modules-values-4.0.0.tgz";
        sha512 = "RDxHkAiEGI78gS2ofyvCsu7iycRv7oqw5xMWn9iMoR0N/7mf9D50ecQqUo5BZ9Zh2vH4bCUR/ktCqbB9m8vJjQ==";
      };
    };
    "postcss-nested-6.2.0" = {
      name = "postcss-nested";
      packageName = "postcss-nested";
      version = "6.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-nested/-/postcss-nested-6.2.0.tgz";
        sha512 = "HQbt28KulC5AJzG+cZtj9kvKB93CFCdLvog1WFLf1D+xmMvPGlBstkpTEZfK5+AN9hfJocyBFCNiqyS48bpgzQ==";
      };
    };
    "postcss-normalize-charset-5.1.0" = {
      name = "postcss-normalize-charset";
      packageName = "postcss-normalize-charset";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-charset/-/postcss-normalize-charset-5.1.0.tgz";
        sha512 = "mSgUJ+pd/ldRGVx26p2wz9dNZ7ji6Pn8VWBajMXFf8jk7vUoSrZ2lt/wZR7DtlZYKesmZI680qjr2CeFF2fbUg==";
      };
    };
    "postcss-normalize-display-values-5.1.0" = {
      name = "postcss-normalize-display-values";
      packageName = "postcss-normalize-display-values";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-display-values/-/postcss-normalize-display-values-5.1.0.tgz";
        sha512 = "WP4KIM4o2dazQXWmFaqMmcvsKmhdINFblgSeRgn8BJ6vxaMyaJkwAzpPpuvSIoG/rmX3M+IrRZEz2H0glrQNEA==";
      };
    };
    "postcss-normalize-positions-5.1.1" = {
      name = "postcss-normalize-positions";
      packageName = "postcss-normalize-positions";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-positions/-/postcss-normalize-positions-5.1.1.tgz";
        sha512 = "6UpCb0G4eofTCQLFVuI3EVNZzBNPiIKcA1AKVka+31fTVySphr3VUgAIULBhxZkKgwLImhzMR2Bw1ORK+37INg==";
      };
    };
    "postcss-normalize-repeat-style-5.1.1" = {
      name = "postcss-normalize-repeat-style";
      packageName = "postcss-normalize-repeat-style";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-repeat-style/-/postcss-normalize-repeat-style-5.1.1.tgz";
        sha512 = "mFpLspGWkQtBcWIRFLmewo8aC3ImN2i/J3v8YCFUwDnPu3Xz4rLohDO26lGjwNsQxB3YF0KKRwspGzE2JEuS0g==";
      };
    };
    "postcss-normalize-string-5.1.0" = {
      name = "postcss-normalize-string";
      packageName = "postcss-normalize-string";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-string/-/postcss-normalize-string-5.1.0.tgz";
        sha512 = "oYiIJOf4T9T1N4i+abeIc7Vgm/xPCGih4bZz5Nm0/ARVJ7K6xrDlLwvwqOydvyL3RHNf8qZk6vo3aatiw/go3w==";
      };
    };
    "postcss-normalize-timing-functions-5.1.0" = {
      name = "postcss-normalize-timing-functions";
      packageName = "postcss-normalize-timing-functions";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-timing-functions/-/postcss-normalize-timing-functions-5.1.0.tgz";
        sha512 = "DOEkzJ4SAXv5xkHl0Wa9cZLF3WCBhF3o1SKVxKQAa+0pYKlueTpCgvkFAHfk+Y64ezX9+nITGrDZeVGgITJXjg==";
      };
    };
    "postcss-normalize-unicode-5.1.1" = {
      name = "postcss-normalize-unicode";
      packageName = "postcss-normalize-unicode";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-unicode/-/postcss-normalize-unicode-5.1.1.tgz";
        sha512 = "qnCL5jzkNUmKVhZoENp1mJiGNPcsJCs1aaRmURmeJGES23Z/ajaln+EPTD+rBeNkSryI+2WTdW+lwcVdOikrpA==";
      };
    };
    "postcss-normalize-url-5.1.0" = {
      name = "postcss-normalize-url";
      packageName = "postcss-normalize-url";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-url/-/postcss-normalize-url-5.1.0.tgz";
        sha512 = "5upGeDO+PVthOxSmds43ZeMeZfKH+/DKgGRD7TElkkyS46JXAUhMzIKiCa7BabPeIy3AQcTkXwVVN7DbqsiCew==";
      };
    };
    "postcss-normalize-whitespace-5.1.1" = {
      name = "postcss-normalize-whitespace";
      packageName = "postcss-normalize-whitespace";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-normalize-whitespace/-/postcss-normalize-whitespace-5.1.1.tgz";
        sha512 = "83ZJ4t3NUDETIHTa3uEg6asWjSBYL5EdkVB0sDncx9ERzOKBVJIUeDO9RyA9Zwtig8El1d79HBp0JEi8wvGQnA==";
      };
    };
    "postcss-ordered-values-5.1.3" = {
      name = "postcss-ordered-values";
      packageName = "postcss-ordered-values";
      version = "5.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-ordered-values/-/postcss-ordered-values-5.1.3.tgz";
        sha512 = "9UO79VUhPwEkzbb3RNpqqghc6lcYej1aveQteWY+4POIwlqkYE21HKWaLDF6lWNuqCobEAyTovVhtI32Rbv2RQ==";
      };
    };
    "postcss-reduce-initial-5.1.2" = {
      name = "postcss-reduce-initial";
      packageName = "postcss-reduce-initial";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-reduce-initial/-/postcss-reduce-initial-5.1.2.tgz";
        sha512 = "dE/y2XRaqAi6OvjzD22pjTUQ8eOfc6m/natGHgKFBK9DxFmIm69YmaRVQrGgFlEfc1HePIurY0TmDeROK05rIg==";
      };
    };
    "postcss-reduce-transforms-5.1.0" = {
      name = "postcss-reduce-transforms";
      packageName = "postcss-reduce-transforms";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-reduce-transforms/-/postcss-reduce-transforms-5.1.0.tgz";
        sha512 = "2fbdbmgir5AvpW9RLtdONx1QoYG2/EtqpNQbFASDlixBbAYuTcJ0dECwlqNqH7VbaUnEnh8SrxOe2sRIn24XyQ==";
      };
    };
    "postcss-selector-parser-6.0.10" = {
      name = "postcss-selector-parser";
      packageName = "postcss-selector-parser";
      version = "6.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-selector-parser/-/postcss-selector-parser-6.0.10.tgz";
        sha512 = "IQ7TZdoaqbT+LCpShg46jnZVlhWD2w6iQYAcYXfHARZ7X1t/UGhhceQDs5X0cGqKvYlHNOuv7Oa1xmb0oQuA3w==";
      };
    };
    "postcss-selector-parser-6.1.2" = {
      name = "postcss-selector-parser";
      packageName = "postcss-selector-parser";
      version = "6.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-selector-parser/-/postcss-selector-parser-6.1.2.tgz";
        sha512 = "Q8qQfPiZ+THO/3ZrOrO0cJJKfpYCagtMUkXbnEfmgUjwXg6z/WBeOyS9APBBPCTSiDV+s4SwQGu8yFsiMRIudg==";
      };
    };
    "postcss-svgo-5.1.0" = {
      name = "postcss-svgo";
      packageName = "postcss-svgo";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-svgo/-/postcss-svgo-5.1.0.tgz";
        sha512 = "D75KsH1zm5ZrHyxPakAxJWtkyXew5qwS70v56exwvw542d9CRtTo78K0WeFxZB4G7JXKKMbEZtZayTGdIky/eA==";
      };
    };
    "postcss-unique-selectors-5.1.1" = {
      name = "postcss-unique-selectors";
      packageName = "postcss-unique-selectors";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-unique-selectors/-/postcss-unique-selectors-5.1.1.tgz";
        sha512 = "5JiODlELrz8L2HwxfPnhOWZYWDxVHWL83ufOv84NrcgipI7TaeRsatAhK4Tr2/ZiYldpK/wBvw5BD3qfaK96GA==";
      };
    };
    "postcss-value-parser-4.2.0" = {
      name = "postcss-value-parser";
      packageName = "postcss-value-parser";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-value-parser/-/postcss-value-parser-4.2.0.tgz";
        sha512 = "1NNCs6uurfkVbeXG4S8JFT9t19m45ICnif8zWLd5oPSZ50QnwMfK+H3jv408d4jw/7Bttv5axS5IiHoLaVNHeQ==";
      };
    };
    "promise.series-0.2.0" = {
      name = "promise.series";
      packageName = "promise.series";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/promise.series/-/promise.series-0.2.0.tgz";
        sha512 = "VWQJyU2bcDTgZw8kpfBpB/ejZASlCrzwz5f2hjb/zlujOEB4oeiAhHygAWq8ubsX2GVkD4kCU5V2dwOTaCY5EQ==";
      };
    };
    "queue-microtask-1.2.3" = {
      name = "queue-microtask";
      packageName = "queue-microtask";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/queue-microtask/-/queue-microtask-1.2.3.tgz";
        sha512 = "NuaNSa6flKT5JaSYQzJok04JzTL1CA6aGhv5rfLW3PgqA+M2ChpZQnAC8h8i4ZFkBS8X5RqkDBHA7r4hej3K9A==";
      };
    };
    "randombytes-2.1.0" = {
      name = "randombytes";
      packageName = "randombytes";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/randombytes/-/randombytes-2.1.0.tgz";
        sha512 = "vYl3iOX+4CKUWuxGi9Ukhie6fsqXqS9FE2Zaic4tNFD2N2QQaXOMFbuKK4QmDHC0JO6B1Zp41J0LpT0oR68amQ==";
      };
    };
    "read-cache-1.0.0" = {
      name = "read-cache";
      packageName = "read-cache";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-cache/-/read-cache-1.0.0.tgz";
        sha512 = "Owdv/Ft7IjOgm/i0xvNDZ1LrRANRfew4b2prF3OWMQLxLfu3bS8FVhCsrSCMK4lR56Y9ya+AThoTpDCTxCmpRA==";
      };
    };
    "readdirp-3.6.0" = {
      name = "readdirp";
      packageName = "readdirp";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readdirp/-/readdirp-3.6.0.tgz";
        sha512 = "hOS089on8RduqdbhvQ5Z37A0ESjsqz6qnRcffsMU3495FuTdqSm+7bhJ29JvIOsBDEEnan5DPu9t3To9VRlMzA==";
      };
    };
    "resolve-1.22.8" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.22.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.22.8.tgz";
        sha512 = "oKWePCxqpd6FlLvGV1VU0x7bkPmmCNolxzjMf4NczoDnQcIWrAF+cPtZn5i6n+RfD2d9i0tzpKnG6Yk168yIyw==";
      };
    };
    "resolve-from-5.0.0" = {
      name = "resolve-from";
      packageName = "resolve-from";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-from/-/resolve-from-5.0.0.tgz";
        sha512 = "qYg9KP24dD5qka9J47d0aVky0N+b4fTU89LN9iDnjB5waksiC49rvMB0PrUJQGoTmH50XPiqOvAjDfaijGxYZw==";
      };
    };
    "reusify-1.0.4" = {
      name = "reusify";
      packageName = "reusify";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/reusify/-/reusify-1.0.4.tgz";
        sha512 = "U9nH88a3fc/ekCF1l0/UP1IosiuIjyTh7hBvXVMHYgVcfGvt897Xguj2UOLDeI5BG2m7/uwyaLVT6fbtCwTyzw==";
      };
    };
    "rollup-4.24.3" = {
      name = "rollup";
      packageName = "rollup";
      version = "4.24.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/rollup/-/rollup-4.24.3.tgz";
        sha512 = "HBW896xR5HGmoksbi3JBDtmVzWiPAYqp7wip50hjQ67JbDz61nyoMPdqu1DvVW9asYb2M65Z20ZHsyJCMqMyDg==";
      };
    };
    "rollup-plugin-postcss-4.0.2" = {
      name = "rollup-plugin-postcss";
      packageName = "rollup-plugin-postcss";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rollup-plugin-postcss/-/rollup-plugin-postcss-4.0.2.tgz";
        sha512 = "05EaY6zvZdmvPUDi3uCcAQoESDcYnv8ogJJQRp6V5kZ6J6P7uAVJlrTZcaaA20wTH527YTnKfkAoPxWI/jPp4w==";
      };
    };
    "rollup-pluginutils-2.8.2" = {
      name = "rollup-pluginutils";
      packageName = "rollup-pluginutils";
      version = "2.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rollup-pluginutils/-/rollup-pluginutils-2.8.2.tgz";
        sha512 = "EEp9NhnUkwY8aif6bxgovPHMoMoNr2FulJziTndpt5H9RdwC47GSGuII9XxpSdzVGM0GWrNPHV6ie1LTNJPaLQ==";
      };
    };
    "run-parallel-1.2.0" = {
      name = "run-parallel";
      packageName = "run-parallel";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/run-parallel/-/run-parallel-1.2.0.tgz";
        sha512 = "5l4VyZR86LZ/lDxZTR6jqL8AFE2S0IFLMP26AbjsLVADxHdhB/c0GUsH+y39UfCi3dzz8OlQuPmnaJOMoDHQBA==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "safe-identifier-0.4.2" = {
      name = "safe-identifier";
      packageName = "safe-identifier";
      version = "0.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-identifier/-/safe-identifier-0.4.2.tgz";
        sha512 = "6pNbSMW6OhAi9j+N8V+U715yBQsaWJ7eyEUaOrawX+isg5ZxhUlV1NipNtgaKHmFGiABwt+ZF04Ii+3Xjkg+8w==";
      };
    };
    "serialize-javascript-6.0.2" = {
      name = "serialize-javascript";
      packageName = "serialize-javascript";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/serialize-javascript/-/serialize-javascript-6.0.2.tgz";
        sha512 = "Saa1xPByTTq2gdeFZYLLo+RFE35NHZkAbqZeWNd3BpzppeVisAqpDjcp8dyf6uIvEqJRd46jemmyA4iFIeVk8g==";
      };
    };
    "shebang-command-2.0.0" = {
      name = "shebang-command";
      packageName = "shebang-command";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-command/-/shebang-command-2.0.0.tgz";
        sha512 = "kHxr2zZpYtdmrN1qDjrrX/Z1rR1kG8Dx+gkpK1G4eXmvXswmcE1hTWBWYUzlraYw1/yZp6YuDY77YtvbN0dmDA==";
      };
    };
    "shebang-regex-3.0.0" = {
      name = "shebang-regex";
      packageName = "shebang-regex";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-3.0.0.tgz";
        sha512 = "7++dFhtcx3353uBaq8DDR4NuxBetBzC7ZQOhmTQInHEd6bSrXdiEyzCvG07Z44UYdLShWUyXt5M/yhz8ekcb1A==";
      };
    };
    "signal-exit-4.1.0" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-4.1.0.tgz";
        sha512 = "bzyZ1e88w9O1iNJbKnOlvYTrWPDl46O1bG0D3XInv+9tkPrxrN8jUUTiFlDkkmKWgn1M6CfIA13SuGqOa9Korw==";
      };
    };
    "smob-1.5.0" = {
      name = "smob";
      packageName = "smob";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/smob/-/smob-1.5.0.tgz";
        sha512 = "g6T+p7QO8npa+/hNx9ohv1E5pVCmWrVCUzUXJyLdMmftX6ER0oiWY/w9knEonLpnOp6b6FenKnMfR8gqwWdwig==";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "source-map-js-1.2.1" = {
      name = "source-map-js";
      packageName = "source-map-js";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-js/-/source-map-js-1.2.1.tgz";
        sha512 = "UXWMKhLOwVKb728IUtQPXxfYU+usdybtUrK/8uGE8CQMvrhOpwvzDBwj0QhSL7MQc7vIsISBG8VQ8+IDQxpfQA==";
      };
    };
    "source-map-support-0.5.21" = {
      name = "source-map-support";
      packageName = "source-map-support";
      version = "0.5.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-support/-/source-map-support-0.5.21.tgz";
        sha512 = "uBHU3L3czsIyYXKX88fdrGovxdSCoTGDRZ6SYXtSRxLZUzHg5P/66Ht6uoUlHu9EZod+inXhKo3qQgwXUT/y1w==";
      };
    };
    "stable-0.1.8" = {
      name = "stable";
      packageName = "stable";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/stable/-/stable-0.1.8.tgz";
        sha512 = "ji9qxRnOVfcuLDySj9qzhGSEFVobyt1kIOSkj1qZzYLzq7Tos/oUUWvotUPQLlrsidqsK6tBH89Bc9kL5zHA6w==";
      };
    };
    "string-hash-1.1.3" = {
      name = "string-hash";
      packageName = "string-hash";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-hash/-/string-hash-1.1.3.tgz";
        sha512 = "kJUvRUFK49aub+a7T1nNE66EJbZBMnBgoC1UbCZ5n6bsZKBRga4KgBRTMn/pFkeCZSYtNeSyMxPDM0AXWELk2A==";
      };
    };
    "string-width-4.2.3" = {
      name = "string-width";
      packageName = "string-width";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-4.2.3.tgz";
        sha512 = "wKyQRQpjJ0sIp62ErSZdGsjMJWsap5oRNihHhu6G7JVO/9jIB6UyevL+tXuOqrng8j/cxKTWyWUwvSTriiZz/g==";
      };
    };
    "string-width-5.1.2" = {
      name = "string-width";
      packageName = "string-width";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-5.1.2.tgz";
        sha512 = "HnLOCR3vjcY8beoNLtcjZ5/nxn2afmME6lhrDrebokqMap+XbeW8n9TXpPDOqdGK5qcI3oT0GKTW6wC7EMiVqA==";
      };
    };
    "string-width-cjs-4.2.3" = {
      name = "string-width-cjs";
      packageName = "string-width-cjs";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-4.2.3.tgz";
        sha512 = "wKyQRQpjJ0sIp62ErSZdGsjMJWsap5oRNihHhu6G7JVO/9jIB6UyevL+tXuOqrng8j/cxKTWyWUwvSTriiZz/g==";
      };
    };
    "strip-ansi-6.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz";
        sha512 = "Y38VPSHcqkFrCpFnQ9vuSXmquuv5oXOKpGeT6aGrr3o3Gc9AlVa6JBfUSOCnbxGGZF+/0ooI7KrPuUSztUdU5A==";
      };
    };
    "strip-ansi-7.1.0" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "7.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-7.1.0.tgz";
        sha512 = "iq6eVVI64nQQTRYq2KtEg2d2uU7LElhTJwsH4YzIHZshxlgZms/wIc4VoDQTlG/IvVIrBKG06CrZnp0qv7hkcQ==";
      };
    };
    "strip-ansi-cjs-6.0.1" = {
      name = "strip-ansi-cjs";
      packageName = "strip-ansi-cjs";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz";
        sha512 = "Y38VPSHcqkFrCpFnQ9vuSXmquuv5oXOKpGeT6aGrr3o3Gc9AlVa6JBfUSOCnbxGGZF+/0ooI7KrPuUSztUdU5A==";
      };
    };
    "style-inject-0.3.0" = {
      name = "style-inject";
      packageName = "style-inject";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/style-inject/-/style-inject-0.3.0.tgz";
        sha512 = "IezA2qp+vcdlhJaVm5SOdPPTUu0FCEqfNSli2vRuSIBbu5Nq5UvygTk/VzeCqfLz2Atj3dVII5QBKGZRZ0edzw==";
      };
    };
    "stylehacks-5.1.1" = {
      name = "stylehacks";
      packageName = "stylehacks";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/stylehacks/-/stylehacks-5.1.1.tgz";
        sha512 = "sBpcd5Hx7G6seo7b1LkpttvTz7ikD0LlH5RmdcBNb6fFR0Fl7LQwHDFr300q4cwUqi+IYrFGmsIHieMBfnN/Bw==";
      };
    };
    "sucrase-3.35.0" = {
      name = "sucrase";
      packageName = "sucrase";
      version = "3.35.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sucrase/-/sucrase-3.35.0.tgz";
        sha512 = "8EbVDiu9iN/nESwxeSxDKe0dunta1GOlHufmSSXxMD2z2/tMZpDMpvXQGsc+ajGo8y2uYUmixaSRUc/QPoQ0GA==";
      };
    };
    "supports-color-7.2.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-7.2.0.tgz";
        sha512 = "qpCAvRl9stuOHveKsn7HncJRvv501qIacKzQlO/+Lwxc9+0q2wLyv4Dfvt80/DPn2pqOBsJdDiogXGR9+OvwRw==";
      };
    };
    "supports-preserve-symlinks-flag-1.0.0" = {
      name = "supports-preserve-symlinks-flag";
      packageName = "supports-preserve-symlinks-flag";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-preserve-symlinks-flag/-/supports-preserve-symlinks-flag-1.0.0.tgz";
        sha512 = "ot0WnXS9fgdkgIcePe6RHNk1WA8+muPa6cSjeR3V8K27q9BB1rTE3R1p7Hv0z1ZyAc8s6Vvv8DIyWf681MAt0w==";
      };
    };
    "svgo-2.8.0" = {
      name = "svgo";
      packageName = "svgo";
      version = "2.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/svgo/-/svgo-2.8.0.tgz";
        sha512 = "+N/Q9kV1+F+UeWYoSiULYo4xYSDQlTgb+ayMobAXPwMnLvop7oxKMo9OzIrX5x3eS4L4f2UHhc9axXwY8DpChg==";
      };
    };
    "tailwindcss-3.4.14" = {
      name = "tailwindcss";
      packageName = "tailwindcss";
      version = "3.4.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/tailwindcss/-/tailwindcss-3.4.14.tgz";
        sha512 = "IcSvOcTRcUtQQ7ILQL5quRDg7Xs93PdJEk1ZLbhhvJc7uj/OAhYOnruEiwnGgBvUtaUAJ8/mhSw1o8L2jCiENA==";
      };
    };
    "terser-5.36.0" = {
      name = "terser";
      packageName = "terser";
      version = "5.36.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/terser/-/terser-5.36.0.tgz";
        sha512 = "IYV9eNMuFAV4THUspIRXkLakHnV6XO7FEdtKjf/mDyrnqUg9LnlOn6/RwRvM9SZjR4GUq8Nk8zj67FzVARr74w==";
      };
    };
    "thenify-3.3.1" = {
      name = "thenify";
      packageName = "thenify";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/thenify/-/thenify-3.3.1.tgz";
        sha512 = "RVZSIV5IG10Hk3enotrhvz0T9em6cyHBLkH/YAZuKqd8hRkKhSfCGIcP2KUY0EPxndzANBmNllzWPwak+bheSw==";
      };
    };
    "thenify-all-1.6.0" = {
      name = "thenify-all";
      packageName = "thenify-all";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/thenify-all/-/thenify-all-1.6.0.tgz";
        sha512 = "RNxQH/qI8/t3thXJDwcstUO4zeqo64+Uy/+sNVRBx4Xn2OX+OZ9oP+iJnNFqplFra2ZUVeKCSa2oVWi3T4uVmA==";
      };
    };
    "to-regex-range-5.0.1" = {
      name = "to-regex-range";
      packageName = "to-regex-range";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-regex-range/-/to-regex-range-5.0.1.tgz";
        sha512 = "65P7iz6X5yEr1cwcgvQxbbIw7Uk3gOy5dIdtZ4rDveLqhrdJP+Li/Hx6tyK0NEb+2GCyneCMJiGqrADCSNk8sQ==";
      };
    };
    "ts-interface-checker-0.1.13" = {
      name = "ts-interface-checker";
      packageName = "ts-interface-checker";
      version = "0.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/ts-interface-checker/-/ts-interface-checker-0.1.13.tgz";
        sha512 = "Y/arvbn+rrz3JCKl9C4kVNfTfSm2/mEp5FSz5EsZSANGPSlQrpRI5M4PKF+mJnE52jOO90PnPSc3Ur3bTQw0gA==";
      };
    };
    "ts-node-10.9.2" = {
      name = "ts-node";
      packageName = "ts-node";
      version = "10.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ts-node/-/ts-node-10.9.2.tgz";
        sha512 = "f0FFpIdcHgn8zcPSbf1dRevwt047YMnaiJM3u2w2RewrB+fob/zePZcrOyQoLMMO7aBIddLcQIEK5dYjkLnGrQ==";
      };
    };
    "tslib-2.8.1" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.8.1.tgz";
        sha512 = "oJFu94HQb+KVduSUQL7wnpmqnfmLsOA/nAh6b6EH0wCEoK0/mPeXU6c3wKDV83MkOuHPRHtSXKKU99IBazS/2w==";
      };
    };
    "typescript-5.6.3" = {
      name = "typescript";
      packageName = "typescript";
      version = "5.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript/-/typescript-5.6.3.tgz";
        sha512 = "hjcS1mhfuyi4WW8IWtjP7brDrG2cuDZukyrYrSauoXGNgx0S7zceP07adYkJycEr56BOUTNPzbInooiN3fn1qw==";
      };
    };
    "undici-types-6.19.8" = {
      name = "undici-types";
      packageName = "undici-types";
      version = "6.19.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/undici-types/-/undici-types-6.19.8.tgz";
        sha512 = "ve2KP6f/JnbPBFyobGHuerC9g1FYGn/F8n1LWTwNxCEzd6IfqTwUQcNXgEtmmQ6DlRrC1hrSrBnCZPokRrDHjw==";
      };
    };
    "update-browserslist-db-1.1.1" = {
      name = "update-browserslist-db";
      packageName = "update-browserslist-db";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/update-browserslist-db/-/update-browserslist-db-1.1.1.tgz";
        sha512 = "R8UzCaa9Az+38REPiJ1tXlImTJXlVfgHZsglwBD/k6nj76ctsH1E3q4doGrukiLQd3sGQYu56r5+lo5r94l29A==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha512 = "EPD5q1uXyFxJpCrLnCc1nHnq3gOa6DZBocAIiI2TaSCA7VCJ1UJDMagCzIkXNsUYfD1daK//LTEQ8xiIbrHtcw==";
      };
    };
    "v8-compile-cache-lib-3.0.1" = {
      name = "v8-compile-cache-lib";
      packageName = "v8-compile-cache-lib";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/v8-compile-cache-lib/-/v8-compile-cache-lib-3.0.1.tgz";
        sha512 = "wa7YjyUGfNZngI/vtK0UHAN+lgDCxBPCylVXGp0zu59Fz5aiGtNXaq3DhIov063MorB+VfufLh3JlF2KdTK3xg==";
      };
    };
    "which-2.0.2" = {
      name = "which";
      packageName = "which";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-2.0.2.tgz";
        sha512 = "BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==";
      };
    };
    "wrap-ansi-8.1.0" = {
      name = "wrap-ansi";
      packageName = "wrap-ansi";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-8.1.0.tgz";
        sha512 = "si7QWI6zUMq56bESFvagtmzMdGOtoxfR+Sez11Mobfc7tm+VkUckk9bW2UeffTGVUbOksxmSw0AA2gs8g71NCQ==";
      };
    };
    "wrap-ansi-cjs-7.0.0" = {
      name = "wrap-ansi-cjs";
      packageName = "wrap-ansi-cjs";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-7.0.0.tgz";
        sha512 = "YVGIj2kamLSTxw6NsZjoBxfSwsn0ycdesmc4p+Q21c5zPuZ1pl+NfxVdxPtdHvmNVOQ6XSYG4AUtyt/Fi7D16Q==";
      };
    };
    "yaml-1.10.2" = {
      name = "yaml";
      packageName = "yaml";
      version = "1.10.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/yaml/-/yaml-1.10.2.tgz";
        sha512 = "r3vXyErRCYJ7wg28yvBY5VSoAF8ZvlcW9/BwUzEtUsjvX/DKs24dIkuwjtuprwJJHsbyUbLApepYTR1BN4uHrg==";
      };
    };
    "yaml-2.6.0" = {
      name = "yaml";
      packageName = "yaml";
      version = "2.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yaml/-/yaml-2.6.0.tgz";
        sha512 = "a6ae//JvKDEra2kdi1qzCyrJW/WZCgFi8ydDV+eXExl95t+5R+ijnqHJbz9tmMh8FUjx3iv2fCQ4dclAQlO2UQ==";
      };
    };
    "yn-3.1.1" = {
      name = "yn";
      packageName = "yn";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yn/-/yn-3.1.1.tgz";
        sha512 = "Ux4ygGWsu2c7isFWe8Yu1YluJmqVhxqK2cLXNQA5AcC3QfbGNpM7fu0Y8b/z16pXLnFxZYvWhd3fhBY9DLmC6Q==";
      };
    };
  };
  args = {
    name = "blog";
    packageName = "blog";
    version = "1.0.0";
    src = ./..;
    dependencies = [
      sources."@alloc/quick-lru-5.2.0"
      (sources."@cspotcode/source-map-support-0.8.1" // {
        dependencies = [
          sources."@jridgewell/trace-mapping-0.3.9"
        ];
      })
      sources."@isaacs/cliui-8.0.2"
      sources."@jridgewell/gen-mapping-0.3.5"
      sources."@jridgewell/resolve-uri-3.1.2"
      sources."@jridgewell/set-array-1.2.1"
      sources."@jridgewell/source-map-0.3.6"
      sources."@jridgewell/sourcemap-codec-1.5.0"
      sources."@jridgewell/trace-mapping-0.3.25"
      sources."@nodelib/fs.scandir-2.1.5"
      sources."@nodelib/fs.stat-2.0.5"
      sources."@nodelib/fs.walk-1.2.8"
      sources."@rollup/plugin-terser-0.4.4"
      sources."@swc/core-1.7.42"
      sources."@swc/counter-0.1.3"
      sources."@swc/helpers-0.5.13"
      sources."@swc/types-0.1.13"
      sources."@swc/wasm-1.7.42"
      sources."@tailwindcss/typography-0.5.15"
      sources."@trysound/sax-0.2.0"
      sources."@tsconfig/node10-1.0.11"
      sources."@tsconfig/node12-1.0.11"
      sources."@tsconfig/node14-1.0.3"
      sources."@tsconfig/node16-1.0.4"
      sources."@types/estree-1.0.6"
      sources."@types/node-22.8.6"
      sources."acorn-8.14.0"
      sources."acorn-walk-8.3.4"
      sources."ansi-regex-5.0.1"
      sources."ansi-styles-4.3.0"
      sources."any-promise-1.3.0"
      sources."anymatch-3.1.3"
      sources."arg-4.1.3"
      sources."autoprefixer-10.4.20"
      sources."balanced-match-1.0.2"
      sources."binary-extensions-2.3.0"
      sources."boolbase-1.0.0"
      sources."brace-expansion-2.0.1"
      sources."braces-3.0.3"
      sources."browserslist-4.24.2"
      sources."buffer-from-1.1.2"
      sources."camelcase-css-2.0.1"
      sources."caniuse-api-3.0.0"
      sources."caniuse-lite-1.0.30001676"
      sources."chalk-4.1.2"
      (sources."chokidar-3.6.0" // {
        dependencies = [
          sources."glob-parent-5.1.2"
        ];
      })
      sources."color-convert-2.0.1"
      sources."color-name-1.1.4"
      sources."colord-2.9.3"
      sources."commander-2.20.3"
      sources."concat-with-sourcemaps-1.1.0"
      sources."create-require-1.1.1"
      sources."cross-spawn-7.0.3"
      sources."css-declaration-sorter-6.4.1"
      sources."css-select-4.3.0"
      sources."css-tree-1.1.3"
      sources."css-what-6.1.0"
      sources."cssesc-3.0.0"
      sources."cssnano-5.1.15"
      sources."cssnano-preset-default-5.2.14"
      sources."cssnano-utils-3.1.0"
      sources."csso-4.2.0"
      sources."didyoumean-1.2.2"
      sources."diff-4.0.2"
      sources."dlv-1.1.3"
      sources."dom-serializer-1.4.1"
      sources."domelementtype-2.3.0"
      sources."domhandler-4.3.1"
      sources."domutils-2.8.0"
      sources."eastasianwidth-0.2.0"
      sources."electron-to-chromium-1.5.50"
      sources."emoji-regex-9.2.2"
      sources."entities-2.2.0"
      sources."escalade-3.2.0"
      sources."estree-walker-0.6.1"
      sources."eventemitter3-4.0.7"
      (sources."fast-glob-3.3.2" // {
        dependencies = [
          sources."glob-parent-5.1.2"
        ];
      })
      sources."fastq-1.17.1"
      sources."fill-range-7.1.1"
      sources."foreground-child-3.3.0"
      sources."fraction.js-4.3.7"
      sources."function-bind-1.1.2"
      sources."generic-names-4.0.0"
      sources."glob-10.4.5"
      sources."glob-parent-6.0.2"
      sources."has-flag-4.0.0"
      sources."hasown-2.0.2"
      sources."icss-replace-symbols-1.1.0"
      sources."icss-utils-5.1.0"
      sources."import-cwd-3.0.0"
      sources."import-from-3.0.0"
      sources."is-binary-path-2.1.0"
      sources."is-core-module-2.15.1"
      sources."is-extglob-2.1.1"
      sources."is-fullwidth-code-point-3.0.0"
      sources."is-glob-4.0.3"
      sources."is-number-7.0.0"
      sources."isexe-2.0.0"
      sources."jackspeak-3.4.3"
      sources."jiti-1.21.6"
      sources."lilconfig-2.1.0"
      sources."lines-and-columns-1.2.4"
      sources."loader-utils-3.3.1"
      sources."lodash.camelcase-4.3.0"
      sources."lodash.castarray-4.4.0"
      sources."lodash.isplainobject-4.0.6"
      sources."lodash.memoize-4.1.2"
      sources."lodash.merge-4.6.2"
      sources."lodash.uniq-4.5.0"
      sources."lru-cache-10.4.3"
      sources."make-error-1.3.6"
      sources."mdn-data-2.0.14"
      sources."merge2-1.4.1"
      sources."micromatch-4.0.8"
      sources."minimatch-9.0.5"
      sources."minipass-7.1.2"
      sources."mz-2.7.0"
      sources."nanoid-3.3.7"
      sources."node-releases-2.0.18"
      sources."normalize-path-3.0.0"
      sources."normalize-range-0.1.2"
      sources."normalize-url-6.1.0"
      sources."nth-check-2.1.1"
      sources."object-assign-4.1.1"
      sources."object-hash-3.0.0"
      sources."p-finally-1.0.0"
      sources."p-queue-6.6.2"
      sources."p-timeout-3.2.0"
      sources."package-json-from-dist-1.0.1"
      sources."path-key-3.1.1"
      sources."path-parse-1.0.7"
      sources."path-scurry-1.11.1"
      sources."picocolors-1.1.1"
      sources."picomatch-2.3.1"
      sources."pify-5.0.0"
      sources."pirates-4.0.6"
      sources."postcss-8.4.47"
      sources."postcss-calc-8.2.4"
      sources."postcss-colormin-5.3.1"
      sources."postcss-convert-values-5.1.3"
      sources."postcss-discard-comments-5.1.2"
      sources."postcss-discard-duplicates-5.1.0"
      sources."postcss-discard-empty-5.1.1"
      sources."postcss-discard-overridden-5.1.0"
      sources."postcss-import-15.1.0"
      sources."postcss-js-4.0.1"
      sources."postcss-load-config-3.1.4"
      sources."postcss-merge-longhand-5.1.7"
      sources."postcss-merge-rules-5.1.4"
      sources."postcss-minify-1.1.0"
      sources."postcss-minify-font-values-5.1.0"
      sources."postcss-minify-gradients-5.1.1"
      sources."postcss-minify-params-5.1.4"
      sources."postcss-minify-selectors-5.2.1"
      sources."postcss-modules-4.3.1"
      sources."postcss-modules-extract-imports-3.1.0"
      sources."postcss-modules-local-by-default-4.0.5"
      sources."postcss-modules-scope-3.2.0"
      sources."postcss-modules-values-4.0.0"
      (sources."postcss-nested-6.2.0" // {
        dependencies = [
          sources."postcss-selector-parser-6.1.2"
        ];
      })
      sources."postcss-normalize-charset-5.1.0"
      sources."postcss-normalize-display-values-5.1.0"
      sources."postcss-normalize-positions-5.1.1"
      sources."postcss-normalize-repeat-style-5.1.1"
      sources."postcss-normalize-string-5.1.0"
      sources."postcss-normalize-timing-functions-5.1.0"
      sources."postcss-normalize-unicode-5.1.1"
      sources."postcss-normalize-url-5.1.0"
      sources."postcss-normalize-whitespace-5.1.1"
      sources."postcss-ordered-values-5.1.3"
      sources."postcss-reduce-initial-5.1.2"
      sources."postcss-reduce-transforms-5.1.0"
      sources."postcss-selector-parser-6.0.10"
      sources."postcss-svgo-5.1.0"
      sources."postcss-unique-selectors-5.1.1"
      sources."postcss-value-parser-4.2.0"
      sources."promise.series-0.2.0"
      sources."queue-microtask-1.2.3"
      sources."randombytes-2.1.0"
      (sources."read-cache-1.0.0" // {
        dependencies = [
          sources."pify-2.3.0"
        ];
      })
      sources."readdirp-3.6.0"
      sources."resolve-1.22.8"
      sources."resolve-from-5.0.0"
      sources."reusify-1.0.4"
      sources."rollup-4.24.3"
      sources."rollup-plugin-postcss-4.0.2"
      sources."rollup-pluginutils-2.8.2"
      sources."run-parallel-1.2.0"
      sources."safe-buffer-5.2.1"
      sources."safe-identifier-0.4.2"
      sources."serialize-javascript-6.0.2"
      sources."shebang-command-2.0.0"
      sources."shebang-regex-3.0.0"
      sources."signal-exit-4.1.0"
      sources."smob-1.5.0"
      sources."source-map-0.6.1"
      sources."source-map-js-1.2.1"
      sources."source-map-support-0.5.21"
      sources."stable-0.1.8"
      sources."string-hash-1.1.3"
      sources."string-width-5.1.2"
      (sources."string-width-cjs-4.2.3" // {
        dependencies = [
          sources."emoji-regex-8.0.0"
          sources."strip-ansi-6.0.1"
        ];
      })
      (sources."strip-ansi-7.1.0" // {
        dependencies = [
          sources."ansi-regex-6.1.0"
        ];
      })
      sources."strip-ansi-cjs-6.0.1"
      sources."style-inject-0.3.0"
      sources."stylehacks-5.1.1"
      (sources."sucrase-3.35.0" // {
        dependencies = [
          sources."commander-4.1.1"
        ];
      })
      sources."supports-color-7.2.0"
      sources."supports-preserve-symlinks-flag-1.0.0"
      (sources."svgo-2.8.0" // {
        dependencies = [
          sources."commander-7.2.0"
        ];
      })
      (sources."tailwindcss-3.4.14" // {
        dependencies = [
          sources."arg-5.0.2"
          (sources."postcss-load-config-4.0.2" // {
            dependencies = [
              sources."lilconfig-3.1.2"
            ];
          })
          sources."postcss-selector-parser-6.1.2"
          sources."yaml-2.6.0"
        ];
      })
      sources."terser-5.36.0"
      sources."thenify-3.3.1"
      sources."thenify-all-1.6.0"
      sources."to-regex-range-5.0.1"
      sources."ts-interface-checker-0.1.13"
      sources."ts-node-10.9.2"
      sources."tslib-2.8.1"
      sources."typescript-5.6.3"
      sources."undici-types-6.19.8"
      sources."update-browserslist-db-1.1.1"
      sources."util-deprecate-1.0.2"
      sources."v8-compile-cache-lib-3.0.1"
      sources."which-2.0.2"
      (sources."wrap-ansi-8.1.0" // {
        dependencies = [
          sources."ansi-styles-6.2.1"
        ];
      })
      (sources."wrap-ansi-cjs-7.0.0" // {
        dependencies = [
          sources."emoji-regex-8.0.0"
          sources."string-width-4.2.3"
          sources."strip-ansi-6.0.1"
        ];
      })
      sources."yaml-1.10.2"
      sources."yn-3.1.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "";
      license = "ISC";
    };
    production = false;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
